


# Pandas

Pandas — пакет для статистической обработки данных, по функциональности близкий к SQL и R. Включает в себя функциональность работы с базами данных и таблицами Excel.

Обычно импорт выглядит так и к нему все привыкли:

In [2]:
import numpy as np
import pandas as pd

## Создание объекта

Создание `Серии` ([`Series`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html#pandas.Series)) путем передачи списка позволет pandas создать целочисленный индекс по умолчанию:

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Создание `DataFrame` ([`DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame)) путем передачи массива NumPy :

In [5]:
# указываем начало временнОго периода и число повторений (дни по умолчанию)
dates = pd.date_range('20120101', periods=600,freq='ME')
dates

DatetimeIndex(['2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30',
               '2012-05-31', '2012-06-30', '2012-07-31', '2012-08-31',
               '2012-09-30', '2012-10-31',
               ...
               '2061-03-31', '2061-04-30', '2061-05-31', '2061-06-30',
               '2061-07-31', '2061-08-31', '2061-09-30', '2061-10-31',
               '2061-11-30', '2061-12-31'],
              dtype='datetime64[ns]', length=600, freq='ME')

In [6]:
np.random.randn(600, 4)

array([[-0.50198798,  0.25683516, -0.5624825 , -0.04570283],
       [ 0.82403425,  0.94331152, -0.75182539,  1.00400931],
       [ 0.69922836,  0.72079433,  0.60113938, -0.34076555],
       ...,
       [-0.80929547,  0.18428169, -0.3992605 , -1.04074592],
       [ 0.50724163, -1.20935232, -2.00745899,  0.10164013],
       [ 0.07657722, -1.19383747,  0.76720203, -0.15285805]])

In [7]:
df = pd.DataFrame(np.random.randn(600, 4), index=dates, columns=['A','B','C','D'])
df

                   A         B         C         D
2012-01-31 -0.311412  0.667208  1.717706 -1.847369
2012-02-29  0.248808  0.044664  0.625272  1.730853
2012-03-31  0.804578 -0.081503  0.553259 -0.262377
2012-04-30  0.476569 -1.458649 -1.171720 -1.773515
2012-05-31 -0.001478 -0.996307  0.367370  0.140001
...              ...       ...       ...       ...
2061-08-31  0.314799 -0.082635 -0.249399  1.087080
2061-09-30 -2.012953  0.601205 -1.177553  1.591242
2061-10-31 -1.242894 -1.331563 -0.762655  0.825453
2061-11-30 -1.192910  0.329820 -0.181624 -0.949195
2061-12-31  0.878295 -0.039897  0.869247  0.218944

[600 rows x 4 columns]

In [16]:
numbers_01 = np.arange(2, 12, 0.5, dtype=np.float32)
print(len(numbers_01))

series_num_01 = pd.Series(numbers_01)
print(series_num_01)

20
0      2.0
1      2.5
2      3.0
3      3.5
4      4.0
5      4.5
6      5.0
7      5.5
8      6.0
9      6.5
10     7.0
11     7.5
12     8.0
13     8.5
14     9.0
15     9.5
16    10.0
17    10.5
18    11.0
19    11.5
dtype: float32

In [17]:
numbers_02 = np.arange(2, 22, 0.5, dtype=np.float32)
print(len(numbers_02))
series_num_02 = pd.Series(numbers_02)
print(series_num_02)

40
0      2.0
1      2.5
2      3.0
3      3.5
4      4.0
5      4.5
6      5.0
7      5.5
8      6.0
9      6.5
10     7.0
11     7.5
12     8.0
13     8.5
14     9.0
15     9.5
16    10.0
17    10.5
18    11.0
19    11.5
20    12.0
21    12.5
22    13.0
23    13.5
24    14.0
25    14.5
26    15.0
27    15.5
28    16.0
29    16.5
30    17.0
31    17.5
32    18.0
33    18.5
34    19.0
35    19.5
36    20.0
37    20.5
38    21.0
39    21.5
dtype: float32

In [19]:
series_num_01 + series_num_02 # при сложении series разной длины, всё что сверх длины короткого Series, заполнится Nan

0      4.0
1      5.0
2      6.0
3      7.0
4      8.0
5      9.0
6     10.0
7     11.0
8     12.0
9     13.0
10    14.0
11    15.0
12    16.0
13    17.0
14    18.0
15    19.0
16    20.0
17    21.0
18    22.0
19    23.0
20     NaN
21     NaN
22     NaN
23     NaN
24     NaN
25     NaN
26     NaN
27     NaN
28     NaN
29     NaN
30     NaN
31     NaN
32     NaN
33     NaN
34     NaN
35     NaN
36     NaN
37     NaN
38     NaN
39     NaN
dtype: float32

In [20]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

Включение категориальных данных в `DataFrame`, см. [введение в категории](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#categorical)

In [21]:
pd.Categorical(["red", "green", "blue", "red"])

['red', 'green', 'blue', 'red']
Categories (3, object): ['blue', 'green', 'red']

In [22]:
dict_py = {'A': 1.,
            'B': pd.Timestamp('20130102'), # временнАя метка
            'C': pd.Series(1, index=list(range(4)), dtype='float32'), # Серия на основе списка
            'D': np.array([3] * 4, dtype='int32'), # массив целых чисел NumPy
            'E': pd.Categorical(["red", "green", "blue", "red"]), # категории
            'F': 'foobar'}

dict_py

{'A': 1.0,
 'B': Timestamp('2013-01-02 00:00:00'),
 'C': 0    1.0
 1    1.0
 2    1.0
 3    1.0
 dtype: float32,
 'D': array([3, 3, 3, 3], dtype=int32),
 'E': ['red', 'green', 'blue', 'red']
 Categories (3, object): ['blue', 'green', 'red'],
 'F': 'foobar'}

Создать [`DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame) можно путем передачи словаря объектов.

In [23]:
df2 = pd.DataFrame(dict_py)
df2

     A          B    C  D      E       F
0  1.0 2013-01-02  1.0  3    red  foobar
1  1.0 2013-01-02  1.0  3  green  foobar
2  1.0 2013-01-02  1.0  3   blue  foobar
3  1.0 2013-01-02  1.0  3    red  foobar

Столбцы итогового [`DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame) имеют разные [типы данных](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#basics-dtypes).

In [24]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

## Просмотр данных

Просмотрим верхние и нижние строки полученного DataFrame:

In [26]:
df.head(15) # вывести первые 10 строк

                   A         B         C         D
2012-01-31 -0.311412  0.667208  1.717706 -1.847369
2012-02-29  0.248808  0.044664  0.625272  1.730853
2012-03-31  0.804578 -0.081503  0.553259 -0.262377
2012-04-30  0.476569 -1.458649 -1.171720 -1.773515
2012-05-31 -0.001478 -0.996307  0.367370  0.140001
2012-06-30  1.585082  0.067398  0.149100  1.236530
2012-07-31  0.606025  0.288407  0.004997  1.208718
2012-08-31 -1.783629 -0.692394 -1.253129  0.472508
2012-09-30  0.469248 -1.174504  0.198428 -0.308379
2012-10-31  0.575168 -0.337926  0.378607  1.549686
2012-11-30 -0.257932 -1.869790  0.075635 -0.810716
2012-12-31 -0.706510 -0.068075  2.874875  0.284778
2013-01-31  0.062229 -0.898127 -0.051427  1.077788
2013-02-28  0.152341 -0.400381 -1.287939  0.213011
2013-03-31  1.757002  0.932732  0.366139  1.903312

In [27]:
df.tail(15) # вывести последние три строки

                   A         B         C         D
2060-10-31  1.564791  0.727158  1.141835  2.821416
2060-11-30  0.412623  0.179233 -0.703159 -0.154326
2060-12-31  0.280233 -0.684128  0.050076 -0.734925
2061-01-31 -1.709198  1.416804  0.626682  0.645801
2061-02-28  0.196612  1.450873  0.712775  0.635733
2061-03-31  1.760953  1.026578  1.879497  0.570918
2061-04-30  0.091172 -0.633736 -0.745920 -0.659835
2061-05-31 -2.060853 -0.316440 -0.324916  1.397315
2061-06-30  0.270393 -1.469325  1.197017  0.587816
2061-07-31  0.268553 -0.601572 -2.080317 -0.779178
2061-08-31  0.314799 -0.082635 -0.249399  1.087080
2061-09-30 -2.012953  0.601205 -1.177553  1.591242
2061-10-31 -1.242894 -1.331563 -0.762655  0.825453
2061-11-30 -1.192910  0.329820 -0.181624 -0.949195
2061-12-31  0.878295 -0.039897  0.869247  0.218944

Отобразим индекс и названия столбцов:

In [28]:
df.index

DatetimeIndex(['2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30',
               '2012-05-31', '2012-06-30', '2012-07-31', '2012-08-31',
               '2012-09-30', '2012-10-31',
               ...
               '2061-03-31', '2061-04-30', '2061-05-31', '2061-06-30',
               '2061-07-31', '2061-08-31', '2061-09-30', '2061-10-31',
               '2061-11-30', '2061-12-31'],
              dtype='datetime64[ns]', length=600, freq='ME')

In [29]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

Метод [`DataFrame.to_numpy()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy) представляет данные в виде массива NumPy, на котором строится DataFrame.

In [32]:
num_arr = df.to_numpy()
num_arr

array([[-0.31141236,  0.66720815,  1.71770558, -1.84736925],
       [ 0.24880839,  0.04466423,  0.62527174,  1.73085341],
       [ 0.80457767, -0.08150252,  0.55325914, -0.26237725],
       ...,
       [-1.24289423, -1.33156308, -0.762655  ,  0.82545307],
       [-1.19290984,  0.32982012, -0.18162357, -0.94919525],
       [ 0.87829494, -0.03989714,  0.86924736,  0.21894361]])

In [36]:
df.to_list()

AttributeError: 'DataFrame' object has no attribute 'to_list'

In [38]:
df.to_numpy().flatten()

array([-0.31141236,  0.66720815,  1.71770558, ..., -0.03989714,
        0.86924736,  0.21894361])

In [40]:
df.to_dict()

{'A': {Timestamp('2012-01-31 00:00:00'): -0.31141236301659725,
  Timestamp('2012-02-29 00:00:00'): 0.24880839036409702,
  Timestamp('2012-03-31 00:00:00'): 0.8045776741791452,
  Timestamp('2012-04-30 00:00:00'): 0.47656882150960644,
  Timestamp('2012-05-31 00:00:00'): -0.0014782057329237718,
  Timestamp('2012-06-30 00:00:00'): 1.5850820616986345,
  Timestamp('2012-07-31 00:00:00'): 0.6060252812910359,
  Timestamp('2012-08-31 00:00:00'): -1.78362879448501,
  Timestamp('2012-09-30 00:00:00'): 0.4692478912799219,
  Timestamp('2012-10-31 00:00:00'): 0.5751684025563769,
  Timestamp('2012-11-30 00:00:00'): -0.2579318089378089,
  Timestamp('2012-12-31 00:00:00'): -0.7065097335002044,
  Timestamp('2013-01-31 00:00:00'): 0.06222924490621912,
  Timestamp('2013-02-28 00:00:00'): 0.1523407260175863,
  Timestamp('2013-03-31 00:00:00'): 1.7570024152267363,
  Timestamp('2013-04-30 00:00:00'): -1.1616086920487436,
  Timestamp('2013-05-31 00:00:00'): 1.0680482362427735,
  Timestamp('2013-06-30 00:00:00'): 1.23555880485748,
  Timestamp('2013-07-31 00:00:00'): -1.2343261321217494,
  Timestamp('2013-08-31 00:00:00'): 0.7302087262887493,
  Timestamp('2013-09-30 00:00:00'): 0.648235270644747,
  Timestamp('2013-10-31 00:00:00'): 2.4390118501883835,
  Timestamp('2013-11-30 00:00:00'): -0.5147734294564702,
  Timestamp('2013-12-31 00:00:00'): 1.2178241892600334,
  Timestamp('2014-01-31 00:00:00'): -1.4360066761916797,
  Timestamp('2014-02-28 00:00:00'): -1.0964260979795095,
  Timestamp('2014-03-31 00:00:00'): -0.2606178651744114,
  Timestamp('2014-04-30 00:00:00'): -0.8642358692378124,
  Timestamp('2014-05-31 00:00:00'): 1.3728999114238722,
  Timestamp('2014-06-30 00:00:00'): -0.35596232706305025,
  Timestamp('2014-07-31 00:00:00'): 0.2551661575247855,
  Timestamp('2014-08-31 00:00:00'): 0.8312668249952769,
  Timestamp('2014-09-30 00:00:00'): 1.497763719080319,
  Timestamp('2014-10-31 00:00:00'): 0.19083896851474902,
  Timestamp('2014-11-30 00:00:00'): 0.679108579544389,
  Timestamp('2014-12-31 00:00:00'): -1.4081561023155469,
  Timestamp('2015-01-31 00:00:00'): -1.4504728152943118,
  Timestamp('2015-02-28 00:00:00'): 1.7340916790019558,
  Timestamp('2015-03-31 00:00:00'): 0.5419389200137634,
  Timestamp('2015-04-30 00:00:00'): -0.8441851269081339,
  Timestamp('2015-05-31 00:00:00'): -0.12042198084191492,
  Timestamp('2015-06-30 00:00:00'): -0.40694346613095395,
  Timestamp('2015-07-31 00:00:00'): 0.6412026454368551,
  Timestamp('2015-08-31 00:00:00'): 0.36367595350390913,
  Timestamp('2015-09-30 00:00:00'): -0.9798818584242798,
  Timestamp('2015-10-31 00:00:00'): -0.2438352656747685,
  Timestamp('2015-11-30 00:00:00'): 0.8567870916479376,
  Timestamp('2015-12-31 00:00:00'): -1.9844003064063223,
  Timestamp('2016-01-31 00:00:00'): 0.23267981506618662,
  Timestamp('2016-02-29 00:00:00'): 0.17582197330673938,
  Timestamp('2016-03-31 00:00:00'): -0.04046121698895487,
  Timestamp('2016-04-30 00:00:00'): 0.1702288503744888,
  Timestamp('2016-05-31 00:00:00'): 0.6871583513759747,
  Timestamp('2016-06-30 00:00:00'): 0.5698745800680974,
  Timestamp('2016-07-31 00:00:00'): 1.8731058441457127,
  Timestamp('2016-08-31 00:00:00'): 0.8755285034550376,
  Timestamp('2016-09-30 00:00:00'): 0.3313228588903121,
  Timestamp('2016-10-31 00:00:00'): -2.197527869271115,
  Timestamp('2016-11-30 00:00:00'): -0.5604303251161843,
  Timestamp('2016-12-31 00:00:00'): -0.12030515926211989,
  Timestamp('2017-01-31 00:00:00'): -1.4330379139163127,
  Timestamp('2017-02-28 00:00:00'): 0.24356058320246382,
  Timestamp('2017-03-31 00:00:00'): 1.92658977826559,
  Timestamp('2017-04-30 00:00:00'): 1.0532515092770922,
  Timestamp('2017-05-31 00:00:00'): -0.2120875949687044,
  Timestamp('2017-06-30 00:00:00'): -1.016351716234981,
  Timestamp('2017-07-31 00:00:00'): -1.134167315023938,
  Timestamp('2017-08-31 00:00:00'): 1.0093197512014396,
  Timestamp('2017-09-30 00:00:00'): -0.5837479468851259,
  Timestamp('2017-10-31 00:00:00'): -1.0520839437769192,
  Timestamp('2017-11-30 00:00:00'): -0.46552134202036083,
  Timestamp('2017-12-31 00:00:00'): -3.8864029053650997,
  Timestamp('2018-01-31 00:00:00'): 0.22127518707127983,
  Timestamp('2018-02-28 00:00:00'): 1.3458416417597585,
  Timestamp('2018-03-31 00:00:00'): 1.3637496867032657,
  Timestamp('2018-04-30 00:00:00'): 1.798731707809307,
  Timestamp('2018-05-31 00:00:00'): -0.5647935359652454,
  Timestamp('2018-06-30 00:00:00'): 0.6899424394264019,
  Timestamp('2018-07-31 00:00:00'): -0.264478163945862,
  Timestamp('2018-08-31 00:00:00'): -1.762234121056315,
  Timestamp('2018-09-30 00:00:00'): -0.648784036707219,
  Timestamp('2018-10-31 00:00:00'): 0.708936560135826,
  Timestamp('2018-11-30 00:00:00'): -0.061690855791631936,
  Timestamp('2018-12-31 00:00:00'): -0.7785050660433471,
  Timestamp('2019-01-31 00:00:00'): 0.6007122003588121,
  Timestamp('2019-02-28 00:00:00'): -0.04816217258227035,
  Timestamp('2019-03-31 00:00:00'): -1.8038986937939192,
  Timestamp('2019-04-30 00:00:00'): -1.2062786597699124,
  Timestamp('2019-05-31 00:00:00'): -0.12706672967914134,
  Timestamp('2019-06-30 00:00:00'): 0.279543025234561,
  Timestamp('2019-07-31 00:00:00'): 0.01988871948818858,
  Timestamp('2019-08-31 00:00:00'): 0.025917193805906676,
  Timestamp('2019-09-30 00:00:00'): 0.526811450787643,
  Timestamp('2019-10-31 00:00:00'): 0.8434752765079322,
  Timestamp('2019-11-30 00:00:00'): -0.34888061200872916,
  Timestamp('2019-12-31 00:00:00'): 0.7820910416405644,
  Timestamp('2020-01-31 00:00:00'): -0.00015018718016969278,
  Timestamp('2020-02-29 00:00:00'): -0.22428941793257887,
  Timestamp('2020-03-31 00:00:00'): 1.5731519123669904,
  Timestamp('2020-04-30 00:00:00'): 0.49950646377784674,
  Timestamp('2020-05-31 00:00:00'): -1.0178949100292913,
  Timestamp('2020-06-30 00:00:00'): 1.26346150351212,
  Timestamp('2020-07-31 00:00:00'): -0.9166886256948772,
  Timestamp('2020-08-31 00:00:00'): 0.1660613149443511,
  Timestamp('2020-09-30 00:00:00'): -0.45292035036741646,
  Timestamp('2020-10-31 00:00:00'): 0.2800088591488581,
  Timestamp('2020-11-30 00:00:00'): -0.09333168132361146,
  Timestamp('2020-12-31 00:00:00'): 0.7512510628450849,
  Timestamp('2021-01-31 00:00:00'): -1.5737861836832951,
  Timestamp('2021-02-28 00:00:00'): 0.9636743505584539,
  Timestamp('2021-03-31 00:00:00'): -0.7884107699702698,
  Timestamp('2021-04-30 00:00:00'): -0.3923212554126751,
  Timestamp('2021-05-31 00:00:00'): -0.22102317201832405,
  Timestamp('2021-06-30 00:00:00'): -0.3789658047580789,
  Timestamp('2021-07-31 00:00:00'): 0.4173565496009987,
  Timestamp('2021-08-31 00:00:00'): 1.2773914555711878,
  Timestamp('2021-09-30 00:00:00'): -0.538533893668342,
  Timestamp('2021-10-31 00:00:00'): -0.7426481651208681,
  Timestamp('2021-11-30 00:00:00'): -0.9092430842408004,
  Timestamp('2021-12-31 00:00:00'): 0.2791226037421056,
  Timestamp('2022-01-31 00:00:00'): -0.0936176671946288,
  Timestamp('2022-02-28 00:00:00'): -0.41477412055373564,
  Timestamp('2022-03-31 00:00:00'): -0.2526131885007579,
  Timestamp('2022-04-30 00:00:00'): -0.8370597388561869,
  Timestamp('2022-05-31 00:00:00'): 2.0256495015164813,
  Timestamp('2022-06-30 00:00:00'): 0.642892220511106,
  Timestamp('2022-07-31 00:00:00'): -1.7026730142483917,
  Timestamp('2022-08-31 00:00:00'): 0.18112429566430094,
  Timestamp('2022-09-30 00:00:00'): -1.2812739129577204,
  Timestamp('2022-10-31 00:00:00'): 1.1615160503904243,
  Timestamp('2022-11-30 00:00:00'): -0.42848256458163014,
  Timestamp('2022-12-31 00:00:00'): -0.5061661067360382,
  Timestamp('2023-01-31 00:00:00'): -2.172324651697605,
  Timestamp('2023-02-28 00:00:00'): -0.5872853654167289,
  Timestamp('2023-03-31 00:00:00'): -0.09332845949162343,
  Timestamp('2023-04-30 00:00:00'): 2.2156083550653216,
  Timestamp('2023-05-31 00:00:00'): 1.262733035120141,
  Timestamp('2023-06-30 00:00:00'): 0.41656086050376323,
  Timestamp('2023-07-31 00:00:00'): -0.6109514781845994,
  Timestamp('2023-08-31 00:00:00'): 0.590151248129295,
  Timestamp('2023-09-30 00:00:00'): -1.755666438649974,
  Timestamp('2023-10-31 00:00:00'): -0.7281492833425428,
  Timestamp('2023-11-30 00:00:00'): 0.37951336410284486,
  Timestamp('2023-12-31 00:00:00'): -0.11924664011057036,
  Timestamp('2024-01-31 00:00:00'): -1.0344000404835287,
  Timestamp('2024-02-29 00:00:00'): 0.21191530266515096,
  Timestamp('2024-03-31 00:00:00'): -0.5216922752763852,
  Timestamp('2024-04-30 00:00:00'): -0.6128446120990898,
  Timestamp('2024-05-31 00:00:00'): 0.0314832486085949,
  Timestamp('2024-06-30 00:00:00'): -0.8984445850118237,
  Timestamp('2024-07-31 00:00:00'): 1.1547095564025947,
  Timestamp('2024-08-31 00:00:00'): -0.026228692215669622,
  Timestamp('2024-09-30 00:00:00'): 0.12890159181174998,
  Timestamp('2024-10-31 00:00:00'): 0.5679963801515069,
  Timestamp('2024-11-30 00:00:00'): -0.16994171374740272,
  Timestamp('2024-12-31 00:00:00'): 0.9231985089997424,
  Timestamp('2025-01-31 00:00:00'): -0.7394150145693172,
  Timestamp('2025-02-28 00:00:00'): -0.7455686261465849,
  Timestamp('2025-03-31 00:00:00'): 2.7462078893895914,
  Timestamp('2025-04-30 00:00:00'): 0.22217328235388048,
  Timestamp('2025-05-31 00:00:00'): 0.617089087438798,
  Timestamp('2025-06-30 00:00:00'): 0.3486656650891123,
  Timestamp('2025-07-31 00:00:00'): 0.8716974882094033,
  Timestamp('2025-08-31 00:00:00'): 0.42329294454847516,
  Timestamp('2025-09-30 00:00:00'): -0.922575561390157,
  Timestamp('2025-10-31 00:00:00'): -1.7814041154288471,
  Timestamp('2025-11-30 00:00:00'): -0.7037834096559682,
  Timestamp('2025-12-31 00:00:00'): 2.593097639553493,
  Timestamp('2026-01-31 00:00:00'): -0.029688348039895264,
  Timestamp('2026-02-28 00:00:00'): -0.815693206611333,
  Timestamp('2026-03-31 00:00:00'): -0.4905050830938787,
  Timestamp('2026-04-30 00:00:00'): -0.3104072579833824,
  Timestamp('2026-05-31 00:00:00'): 1.254003730739229,
  Timestamp('2026-06-30 00:00:00'): -0.9310620325222373,
  Timestamp('2026-07-31 00:00:00'): -0.7696611645227921,
  Timestamp('2026-08-31 00:00:00'): 0.16597208865465224,
  Timestamp('2026-09-30 00:00:00'): -1.4941925290949072,
  Timestamp('2026-10-31 00:00:00'): -1.1267961987291855,
  Timestamp('2026-11-30 00:00:00'): 0.7387157174603602,
  Timestamp('2026-12-31 00:00:00'): -1.657317148509996,
  Timestamp('2027-01-31 00:00:00'): -0.692938069323166,
  Timestamp('2027-02-28 00:00:00'): 0.18700181012462622,
  Timestamp('2027-03-31 00:00:00'): 1.452295093347088,
  Timestamp('2027-04-30 00:00:00'): 0.5369141192374356,
  Timestamp('2027-05-31 00:00:00'): 0.6403604103066525,
  Timestamp('2027-06-30 00:00:00'): -0.014749303945088086,
  Timestamp('2027-07-31 00:00:00'): 1.5984408562452077,
  Timestamp('2027-08-31 00:00:00'): 0.24375563730229113,
  Timestamp('2027-09-30 00:00:00'): -0.8329645429633309,
  Timestamp('2027-10-31 00:00:00'): -0.2385314854152608,
  Timestamp('2027-11-30 00:00:00'): -0.01031823106061962,
  Timestamp('2027-12-31 00:00:00'): 0.8117188050789386,
  Timestamp('2028-01-31 00:00:00'): -0.7340860726247853,
  Timestamp('2028-02-29 00:00:00'): 1.9925081316431983,
  Timestamp('2028-03-31 00:00:00'): 0.48779815877210597,
  Timestamp('2028-04-30 00:00:00'): -0.4164586350233964,
  Timestamp('2028-05-31 00:00:00'): -0.5345062923293004,
  Timestamp('2028-06-30 00:00:00'): -0.4494254935982989,
  Timestamp('2028-07-31 00:00:00'): 0.16172744690807483,
  Timestamp('2028-08-31 00:00:00'): 0.519210126662611,
  Timestamp('2028-09-30 00:00:00'): 0.5140572005278204,
  Timestamp('2028-10-31 00:00:00'): -0.5245280620444306,
  Timestamp('2028-11-30 00:00:00'): 0.7731895669712536,
  Timestamp('2028-12-31 00:00:00'): -0.9616022949411445,
  Timestamp('2029-01-31 00:00:00'): 0.41828629685520885,
  Timestamp('2029-02-28 00:00:00'): -0.8828585536136373,
  Timestamp('2029-03-31 00:00:00'): 0.23879897819311577,
  Timestamp('2029-04-30 00:00:00'): -1.7834111208337031,
  Timestamp('2029-05-31 00:00:00'): -0.8903224369138403,
  Timestamp('2029-06-30 00:00:00'): -0.16207300569103647,
  Timestamp('2029-07-31 00:00:00'): -2.2360268708464446,
  Timestamp('2029-08-31 00:00:00'): 0.13200031772573928,
  Timestamp('2029-09-30 00:00:00'): -0.9097437823186676,
  Timestamp('2029-10-31 00:00:00'): 0.4468375931116211,
  Timestamp('2029-11-30 00:00:00'): -1.1893458036833886,
  Timestamp('2029-12-31 00:00:00'): 0.1402497547049889,
  Timestamp('2030-01-31 00:00:00'): -1.7823365486878922,
  Timestamp('2030-02-28 00:00:00'): -1.4958316174785167,
  Timestamp('2030-03-31 00:00:00'): 1.0500472751733496,
  Timestamp('2030-04-30 00:00:00'): -1.136070522915209,
  Timestamp('2030-05-31 00:00:00'): 1.0107903494327433,
  Timestamp('2030-06-30 00:00:00'): -1.902048827129657,
  Timestamp('2030-07-31 00:00:00'): -0.3134052975166009,
  Timestamp('2030-08-31 00:00:00'): 1.2801319446132133,
  Timestamp('2030-09-30 00:00:00'): -0.974720487859778,
  Timestamp('2030-10-31 00:00:00'): -0.7737028281552437,
  Timestamp('2030-11-30 00:00:00'): 0.11501340376703365,
  Timestamp('2030-12-31 00:00:00'): 0.3329781901434653,
  Timestamp('2031-01-31 00:00:00'): -0.041548462053583465,
  Timestamp('2031-02-28 00:00:00'): 0.43010799538865313,
  Timestamp('2031-03-31 00:00:00'): -1.1020748115738053,
  Timestamp('2031-04-30 00:00:00'): -1.5267765754819758,
  Timestamp('2031-05-31 00:00:00'): 1.8898242791502544,
  Timestamp('2031-06-30 00:00:00'): -0.987662077986187,
  Timestamp('2031-07-31 00:00:00'): 1.4704914272863043,
  Timestamp('2031-08-31 00:00:00'): -2.0609456873359147,
  Timestamp('2031-09-30 00:00:00'): -0.6600656608532308,
  Timestamp('2031-10-31 00:00:00'): -0.457780473278145,
  Timestamp('2031-11-30 00:00:00'): 0.08219235271649483,
  Timestamp('2031-12-31 00:00:00'): 0.003362159618052688,
  Timestamp('2032-01-31 00:00:00'): 0.2794533544116929,
  Timestamp('2032-02-29 00:00:00'): -0.039392857735651925,
  Timestamp('2032-03-31 00:00:00'): 1.0061623305057905,
  Timestamp('2032-04-30 00:00:00'): 0.23369993914668502,
  Timestamp('2032-05-31 00:00:00'): -0.7022576100831984,
  Timestamp('2032-06-30 00:00:00'): 0.3241138616514118,
  Timestamp('2032-07-31 00:00:00'): -1.5088730426668246,
  Timestamp('2032-08-31 00:00:00'): 1.4113232048612776,
  Timestamp('2032-09-30 00:00:00'): 0.28862157267806693,
  Timestamp('2032-10-31 00:00:00'): -1.858285422689123,
  Timestamp('2032-11-30 00:00:00'): 0.2373696510343803,
  Timestamp('2032-12-31 00:00:00'): 0.39206138679256475,
  Timestamp('2033-01-31 00:00:00'): -0.05118429182585295,
  Timestamp('2033-02-28 00:00:00'): -0.04589525060582293,
  Timestamp('2033-03-31 00:00:00'): -1.0338737909994271,
  Timestamp('2033-04-30 00:00:00'): -0.634192984598988,
  Timestamp('2033-05-31 00:00:00'): 0.6592687772791166,
  Timestamp('2033-06-30 00:00:00'): 0.14360312262548117,
  Timestamp('2033-07-31 00:00:00'): -0.6103038611139124,
  Timestamp('2033-08-31 00:00:00'): 0.3129958628468974,
  Timestamp('2033-09-30 00:00:00'): 0.3481559413150419,
  Timestamp('2033-10-31 00:00:00'): 1.5403490165048779,
  Timestamp('2033-11-30 00:00:00'): -0.49357257208393296,
  Timestamp('2033-12-31 00:00:00'): 0.4077821636722942,
  Timestamp('2034-01-31 00:00:00'): -0.8569903040280057,
  Timestamp('2034-02-28 00:00:00'): -1.590049852853014,
  Timestamp('2034-03-31 00:00:00'): -0.7242726812130903,
  Timestamp('2034-04-30 00:00:00'): -0.15952169420005965,
  Timestamp('2034-05-31 00:00:00'): 0.697555485976857,
  Timestamp('2034-06-30 00:00:00'): -1.163652081183567,
  Timestamp('2034-07-31 00:00:00'): 0.6077122487584301,
  Timestamp('2034-08-31 00:00:00'): 0.0237433869924101,
  Timestamp('2034-09-30 00:00:00'): 0.9800253479325872,
  Timestamp('2034-10-31 00:00:00'): 0.12257084356511665,
  Timestamp('2034-11-30 00:00:00'): 0.07127974785112982,
  Timestamp('2034-12-31 00:00:00'): 0.9610672388771843,
  Timestamp('2035-01-31 00:00:00'): -0.6494794961655816,
  Timestamp('2035-02-28 00:00:00'): -0.8875237166818297,
  Timestamp('2035-03-31 00:00:00'): -0.7310107679465,
  Timestamp('2035-04-30 00:00:00'): -1.0843081663143324,
  Timestamp('2035-05-31 00:00:00'): -0.9365647883987828,
  Timestamp('2035-06-30 00:00:00'): 1.2228814016252945,
  Timestamp('2035-07-31 00:00:00'): -0.30146726288865533,
  Timestamp('2035-08-31 00:00:00'): -0.5440575962580747,
  Timestamp('2035-09-30 00:00:00'): 0.25094089399047786,
  Timestamp('2035-10-31 00:00:00'): -1.1018011724141246,
  Timestamp('2035-11-30 00:00:00'): 0.15656707485011992,
  Timestamp('2035-12-31 00:00:00'): 0.06254603275622075,
  Timestamp('2036-01-31 00:00:00'): 0.6910317096863123,
  Timestamp('2036-02-29 00:00:00'): 0.985367285210683,
  Timestamp('2036-03-31 00:00:00'): 0.41128522501103126,
  Timestamp('2036-04-30 00:00:00'): 0.696475763646732,
  Timestamp('2036-05-31 00:00:00'): -1.230119123699338,
  Timestamp('2036-06-30 00:00:00'): 0.17946920821021053,
  Timestamp('2036-07-31 00:00:00'): 0.47610573873914724,
  Timestamp('2036-08-31 00:00:00'): 0.17632050132616806,
  Timestamp('2036-09-30 00:00:00'): -1.8066427896132065,
  Timestamp('2036-10-31 00:00:00'): 0.8186720621542332,
  Timestamp('2036-11-30 00:00:00'): 0.011469817615571257,
  Timestamp('2036-12-31 00:00:00'): -0.18035175899648248,
  Timestamp('2037-01-31 00:00:00'): 0.295015515483495,
  Timestamp('2037-02-28 00:00:00'): -0.4910601195209611,
  Timestamp('2037-03-31 00:00:00'): -0.27962769589423647,
  Timestamp('2037-04-30 00:00:00'): -2.5271213791494156,
  Timestamp('2037-05-31 00:00:00'): 0.2817260278546298,
  Timestamp('2037-06-30 00:00:00'): -0.19549824536400778,
  Timestamp('2037-07-31 00:00:00'): -0.7912261012092566,
  Timestamp('2037-08-31 00:00:00'): 0.1689254748413564,
  Timestamp('2037-09-30 00:00:00'): 0.2026578597469713,
  Timestamp('2037-10-31 00:00:00'): 0.8216185841311567,
  Timestamp('2037-11-30 00:00:00'): -0.6421513851747339,
  Timestamp('2037-12-31 00:00:00'): -0.13577813014631576,
  Timestamp('2038-01-31 00:00:00'): 1.1559451325470098,
  Timestamp('2038-02-28 00:00:00'): -0.3198621977849934,
  Timestamp('2038-03-31 00:00:00'): -1.6263621409172415,
  Timestamp('2038-04-30 00:00:00'): 0.3563508939754943,
  Timestamp('2038-05-31 00:00:00'): 0.167036502566745,
  Timestamp('2038-06-30 00:00:00'): -0.009214153731462907,
  Timestamp('2038-07-31 00:00:00'): 1.5265370371928264,
  Timestamp('2038-08-31 00:00:00'): 0.6320125012342178,
  Timestamp('2038-09-30 00:00:00'): 0.18324508868624567,
  Timestamp('2038-10-31 00:00:00'): -0.0917750587263893,
  Timestamp('2038-11-30 00:00:00'): -0.6894671667241842,
  Timestamp('2038-12-31 00:00:00'): -0.520058481811221,
  Timestamp('2039-01-31 00:00:00'): -0.5627268075874099,
  Timestamp('2039-02-28 00:00:00'): 0.4218694426197323,
  Timestamp('2039-03-31 00:00:00'): -0.8648454198512514,
  Timestamp('2039-04-30 00:00:00'): -0.04231719723610351,
  Timestamp('2039-05-31 00:00:00'): 0.9673755851844976,
  Timestamp('2039-06-30 00:00:00'): 0.4742710897910322,
  Timestamp('2039-07-31 00:00:00'): 1.895331123029715,
  Timestamp('2039-08-31 00:00:00'): -0.04255967554831289,
  Timestamp('2039-09-30 00:00:00'): -1.4354239159041446,
  Timestamp('2039-10-31 00:00:00'): -0.12695095818371574,
  Timestamp('2039-11-30 00:00:00'): 0.12305383515773144,
  Timestamp('2039-12-31 00:00:00'): 0.890357146110492,
  Timestamp('2040-01-31 00:00:00'): 1.4326934959685167,
  Timestamp('2040-02-29 00:00:00'): -0.1749747664619608,
  Timestamp('2040-03-31 00:00:00'): -0.10756799626085492,
  Timestamp('2040-04-30 00:00:00'): 1.5745582475789657,
  Timestamp('2040-05-31 00:00:00'): -1.5974384832312667,
  Timestamp('2040-06-30 00:00:00'): -0.6637940379057005,
  Timestamp('2040-07-31 00:00:00'): -1.121552761924111,
  Timestamp('2040-08-31 00:00:00'): -0.03220768051240942,
  Timestamp('2040-09-30 00:00:00'): 1.3255604462807542,
  Timestamp('2040-10-31 00:00:00'): -0.2885806863270301,
  Timestamp('2040-11-30 00:00:00'): 0.08393722387373309,
  Timestamp('2040-12-31 00:00:00'): -0.6498466012864116,
  Timestamp('2041-01-31 00:00:00'): -0.2796696007862282,
  Timestamp('2041-02-28 00:00:00'): -1.5913091622680902,
  Timestamp('2041-03-31 00:00:00'): -1.8050893539558863,
  Timestamp('2041-04-30 00:00:00'): 0.26530182614300335,

In [43]:
df.to_json('test_df_to.json')

In [46]:
df.to_csv('test_df_to.csv', index=False)

In [47]:
num_arr.tolist()

[[-0.31141236301659725,
  0.6672081549258488,
  1.717705577810777,
  -1.847369249602086],
 [0.24880839036409702,
  0.04466423042135691,
  0.6252717370432854,
  1.7308534073508526],
 [0.8045776741791452,
  -0.08150251970000674,
  0.5532591421611422,
  -0.26237724572934956],
 [0.47656882150960644,
  -1.458649008780931,
  -1.1717204452748284,
  -1.7735153177457166],
 [-0.0014782057329237718,
  -0.9963074681185808,
  0.36736999245223817,
  0.1400013115859814],
 [1.5850820616986345,
  0.06739843899428061,
  0.1491002517080361,
  1.2365299860546946],
 [0.6060252812910359,
  0.28840673683876106,
  0.004997279011274257,
  1.2087177815366],
 [-1.78362879448501,
  -0.6923941603304775,
  -1.2531291612175828,
  0.47250816535697093],
 [0.4692478912799219,
  -1.1745042208744816,
  0.19842787651696367,
  -0.30837899677364783],
 [0.5751684025563769,
  -0.3379262089334958,
  0.37860739263839055,
  1.5496860242356907],
 [-0.2579318089378089,
  -1.8697896744279086,
  0.07563523560401077,
  -0.8107160003442901],
 [-0.7065097335002044,
  -0.06807541093184333,
  2.8748753043570354,
  0.2847781739296784],
 [0.06222924490621912,
  -0.8981268153802197,
  -0.0514270359019157,
  1.0777876886047066],
 [0.1523407260175863,
  -0.40038089744020244,
  -1.2879394989274395,
  0.21301128688792725],
 [1.7570024152267363,
  0.9327320814244686,
  0.3661390495883998,
  1.9033117521643892],
 [-1.1616086920487436,
  -0.6892155713291694,
  -0.6913943791870377,
  -0.9680439041454971],
 [1.0680482362427735,
  0.8425968242863843,
  0.47709136482537723,
  -0.13964281640679163],
 [1.23555880485748,
  -1.3698565657923756,
  1.3558879776498138,
  -1.046100206059876],
 [-1.2343261321217494,
  -1.731272139938549,
  -0.48661635871982345,
  -1.6928672071927735],
 [0.7302087262887493,
  1.5200723408523158,
  0.9656562354554655,
  0.254180449658564],
 [0.648235270644747,
  -0.899918812123584,
  -0.8253088423210083,
  -0.47709869506682234],
 [2.4390118501883835,
  -2.0416587977423224,
  -0.1693984749043223,
  1.0659346460773131],
 [-0.5147734294564702,
  -1.057012489792468,
  -0.23713975583899338,
  1.216852573962486],
 [1.2178241892600334,
  -0.5476136131755124,
  0.9000665336920435,
  0.8422737309763898],
 [-1.4360066761916797,
  0.7083000810092751,
  -0.24322413181166766,
  0.6380283069824391],
 [-1.0964260979795095,
  0.9653342657778616,
  -0.40006116161265043,
  -0.5362284599334626],
 [-0.2606178651744114,
  0.287749340875323,
  -0.8812415274668561,
  0.5445095369628199],
 [-0.8642358692378124,
  1.3265982509997694,
  0.6173870045362746,
  -0.9950252259004807],
 [1.3728999114238722,
  -0.606106825187379,
  1.3117216375957277,
  0.5698542787672077],
 [-0.35596232706305025,
  0.4653326329891671,
  1.085663896994634,
  0.33874361078053483],
 [0.2551661575247855,
  -0.3118045696567399,
  0.3189011585739505,
  -0.6504442984462486],
 [0.8312668249952769,
  0.10394997518654867,
  1.3322842625145352,
  2.328137297476298],
 [1.497763719080319,
  0.21622705410803708,
  -0.42994312708108895,
  -0.1725632299993471],
 [0.19083896851474902,
  1.021965838367201,
  0.4316634257052834,
  -1.5321696657022648],
 [0.679108579544389,
  0.23756025780325773,
  0.5987533698001529,
  -0.3831119062709948],
 [-1.4081561023155469,
  -0.27557854030702145,
  -0.7765648156249825,
  1.103990198157343],
 [-1.4504728152943118,
  0.5482146929211523,
  1.0295039845967517,
  1.0154801000585254],
 [1.7340916790019558,
  -0.14340656098059237,
  -0.901168123495291,
  0.7230403968274257],
 [0.5419389200137634,
  -0.3847837945004359,
  -0.10459737452942575,
  0.3167986109687931],
 [-0.8441851269081339,
  -1.1156404627660612,
  -0.878017096143606,
  -0.42026086252227546],
 [-0.12042198084191492,
  -0.6037961140350645,
  -1.224079964777205,
  0.2613475392550917],
 [-0.40694346613095395,
  1.8102988596926122,
  1.5287245125005178,
  -0.1289680810916121],
 [0.6412026454368551,
  0.7357629567164199,
  1.1411306949852422,
  -1.4833949449394903],
 [0.36367595350390913,
  -0.050073083474045745,
  0.7207806926648805,
  -0.4954269863023284],
 [-0.9798818584242798,
  1.1294440261715417,
  -0.4129382355533985,
  1.5900335680981508],
 [-0.2438352656747685,
  0.17795395165034425,
  -0.2527330886154537,
  -0.8503524359086739],
 [0.8567870916479376,
  -0.4379112198274321,
  -0.8103134858008133,
  -0.7554943355178497],
 [-1.9844003064063223,
  -0.9653458952967902,
  0.6870479824911789,
  -0.3898174473269279],
 [0.23267981506618662,
  0.02415670869976881,
  0.9316043680598455,
  0.3040813123681678],
 [0.17582197330673938,
  1.426155232549539,
  1.1276488863253527,
  -0.10529723215923667],
 [-0.04046121698895487,
  0.307436092271788,
  0.11584195803961632,
  0.7681295009856046],
 [0.1702288503744888,
  -0.08305247558630958,
  -0.5563439917272884,
  0.1395379508042027],
 [0.6871583513759747,
  -0.3671731976345778,
  0.9925919796330452,
  0.24159362587427097],
 [0.5698745800680974,
  -1.6649561551448087,
  -0.029991071300965465,
  -1.927500127362744],
 [1.8731058441457127,
  1.2640312982513395,
  0.8983890237425826,
  -0.9206076730215423],
 [0.8755285034550376,
  -0.16163102295980727,
  0.5003389484330736,
  -1.8199236001386794],
 [0.3313228588903121,
  -1.0983425967820257,
  -0.09979592956104226,
  -1.5042973020876627],
 [-2.197527869271115,
  -1.348627631093808,
  -0.467894109485332,
  1.3819460784287905],
 [-0.5604303251161843,
  1.039279030724622,
  1.01496675874744,
  -0.29338572837003013],
 [-0.12030515926211989,
  -1.5897989905478986,
  -0.06058330233760086,
  -1.8617097760074848],
 [-1.4330379139163127,
  0.753126048277678,
  -0.7569360994745418,
  -0.3546575057254273],
 [0.24356058320246382,
  -1.0436111009943507,
  1.3643917372821526,
  -0.023506184170179325],
 [1.92658977826559,
  -0.984696135668736,
  -0.22086849324465377,
  0.8723540317897569],
 [1.0532515092770922,
  -0.19127952933249848,
  -1.0394814173018319,
  -2.6238388302835496],
 [-0.2120875949687044,
  -0.1838246070531609,
  -0.26791024861970575,
  -1.100129159976344],
 [-1.016351716234981,
  1.5856608498664888,
  0.651862686162418,
  -0.6941509537968149],
 [-1.134167315023938,
  -0.07111635289337737,
  1.487457591446124,
  0.5252063260631996],
 [1.0093197512014396,
  -0.7088767225566212,
  -0.12003434636272038,
  -0.9039242491980644],
 [-0.5837479468851259,
  0.2739673431031377,
  0.42631206214327455,
  0.622495265998791],
 [-1.0520839437769192,
  1.692875903583624,
  1.3861590450330084,
  0.4055039942016737],
 [-0.46552134202036083,
  0.22088914170332613,
  -0.34430679227364885,
  0.40900681507651315],
 [-3.8864029053650997,
  -1.4660200113467512,
  -0.022690444865289507,
  0.5936221270840655],
 [0.22127518707127983,
  -0.8044383172706912,
  -0.0022373351025522965,
  -1.7003561826397637],
 [1.3458416417597585,
  -1.1244906973219106,
  0.877296975678979,
  0.6107097582971646],
 [1.3637496867032657,
  -0.5455968471281128,
  1.5089269782346055,
  -0.14580735153211605],
 [1.798731707809307,
  -0.2236426907528896,
  -0.5862969094487785,
  0.21237836575570748],
 [-0.5647935359652454,
  0.29479081077712377,
  0.4082343351937351,
  -1.9986253523483861],
 [0.6899424394264019,
  0.10963374166857671,
  1.1056346624473132,
  0.33225130706042727],
 [-0.264478163945862,
  -2.699001573910911,
  0.792215887947109,
  1.0882266444931676],
 [-1.762234121056315,
  -1.0895501642591947,
  -0.9103581500237196,
  0.309848345398578],
 [-0.648784036707219,
  0.07361881464701918,
  0.4574967866798194,
  -0.5940061668403386],
 [0.708936560135826, 1.028003948840729, -1.032918557822221, 1.309560958761207],
 [-0.061690855791631936,
  -0.4599056479536244,
  0.5920157937597695,
  -0.3708799871097965],
 [-0.7785050660433471,
  0.3555618525552783,
  -0.9824961877420999,
  -0.9578566476858852],
 [0.6007122003588121,
  0.24203495953586396,
  -0.6324342241992583,
  -0.19999354080523996],
 [-0.04816217258227035,
  0.32508087484879317,
  -0.526987923914054,
  0.9850107591258033],
 [-1.8038986937939192,
  1.3614587568607013,
  -0.8328757926935556,
  0.5427789531985615],
 [-1.2062786597699124,
  -1.173199884070139,
  -1.4539141478601685,
  2.4480910540103844],
 [-0.12706672967914134,
  0.4895700282744273,
  0.18677140440028145,
  -1.5566311734220373],
 [0.279543025234561,
  1.2687603714389577,
  1.0916265581847213,
  1.4428931398536509],
 [0.01988871948818858,
  -0.027112598437521493,
  -0.17292081800012415,
  -0.4215390131133342],
 [0.025917193805906676,
  0.1189026883856837,
  -0.5988259119551672,
  -0.6733089321780119],
 [0.526811450787643,
  0.8788923382041122,
  -1.0977698998823664,
  -0.30936326941497255],
 [0.8434752765079322,
  1.486539789477943,
  0.861481690437566,
  0.034445388493870154],
 [-0.34888061200872916,
  0.2434988142695355,
  -1.219805785471495,
  -1.214080690865247],
 [0.7820910416405644,
  -0.7381465647912546,
  0.6350559183206539,
  0.9666693476471137],
 [-0.00015018718016969278,
  -1.4920223200218177,
  0.8757634700498257,
  0.7225795571597874],
 [-0.22428941793257887,
  -1.046091768167223,
  0.6540354170583421,
  0.34204944468985665],
 [1.5731519123669904,
  -0.3668050125330134,
  -0.5041624749814947,
  0.36867766161435],
 [0.49950646377784674,
  -0.23141166171732563,
  -0.1261840984755884,
  -0.29007170765145046],
 [-1.0178949100292913,
  -0.3453179956252728,
  -1.059479838385195,
  0.5131665112165028],
 [1.26346150351212,
  -0.06288658507722567,
  -0.022527502875441942,
  0.8282943264243002],
 [-0.9166886256948772,
  1.6320581804966663,
  -0.1326725072104847,
  -1.6914994726159902],
 [0.1660613149443511,
  -0.35949441995161335,
  -0.19861060951741255,
  1.1054265434799229],
 [-0.45292035036741646,
  0.7214117819031712,
  -0.20387623719940715,
  0.4567389646861328],
 [0.2800088591488581,
  0.5439504877898339,
  -0.16074603975790874,
  1.0149036409381744],
 [-0.09333168132361146,
  -0.6657800318039157,
  -0.22521127291075685,
  -0.37436160333768037],
 [0.7512510628450849,
  -0.4308874806974975,
  0.6163986983252434,
  0.0829639460657636],
 [-1.5737861836832951,
  0.718196874906614,
  -0.252707919982385,
  0.8260638352959421],
 [0.9636743505584539,
  1.29598338539588,
  1.9488609780020736,
  -0.12932309248526946],
 [-0.7884107699702698,
  -0.5326699433226137,
  2.2979404070306115,
  0.3256604808884537],
 [-0.3923212554126751,
  -0.7386757563508131,
  -0.05830616767421165,
  -1.7682747270575065],
 [-0.22102317201832405,
  1.3456603475985596,
  -0.5745539761530166,
  1.0762056348252327],
 [-0.3789658047580789,
  -1.1156023561998722,
  -0.08581415987237112,
  0.11636648723567823],
 [0.4173565496009987,
  -0.4825417292388878,
  1.2613625883820447,
  -0.9888261914686327],
 [1.2773914555711878,
  0.2625971051494718,
  0.433695247542854,
  -1.6424164855670484],
 [-0.538533893668342,
  -1.114536867427168,
  0.17310764338814932,
  0.015298239834620841],
 [-0.7426481651208681,
  -0.7666202772834749,
  1.1828818749532037,
  -0.051994147360564756],
 [-0.9092430842408004,
  -1.4814338448465845,
  0.23287178301436523,
  -0.7849040443325179],
 [0.2791226037421056,
  0.5199939102550387,
  0.21273047928208605,
  -0.9393913592442721],
 [-0.0936176671946288,
  -1.5508843578645308,
  0.44958400579440033,
  -0.1726903591451324],
 [-0.41477412055373564,
  1.3009489027856287,
  0.4178621721367827,
  -1.3373010656568836],
 [-0.2526131885007579,
  0.8806287621623267,
  1.2379012632484576,
  0.20118116550381443],
 [-0.8370597388561869,
  0.17112140110334512,
  0.11387878712015811,
  1.748361458904338],
 [2.0256495015164813,
  2.390017164348402,
  -0.4437231033259104,
  -0.863563885147419],
 [0.642892220511106,
  -0.2341590280482602,
  0.09768702313092309,
  -0.3426292566473188],
 [-1.7026730142483917,
  0.11632266430603923,
  1.2572025382572218,
  0.5042512077025862],
 [0.18112429566430094,
  -0.8560112891810266,
  0.07332003854401417,
  -0.39443629471839337],
 [-1.2812739129577204,
  -0.5488073010559782,
  -1.898457795657144,
  -0.4622955425267853],
 [1.1615160503904243,
  -0.3866209156024827,
  -0.3268800281786368,
  0.2876599497753802],
 [-0.42848256458163014,
  -1.6312037475962176,
  -0.3595837715618901,
  -0.20123793176566596],
 [-0.5061661067360382,
  -0.34630706865044203,
  2.1372178630429888,
  0.9388395278296616],
 [-2.172324651697605,
  -0.21086553802176589,
  -0.4941312383549892,
  0.22036186457726645],
 [-0.5872853654167289,
  0.40874558951630674,
  0.6902014907231934,
  -0.35401202626331785],
 [-0.09332845949162343,
  -1.9479282705888183,
  -0.6033506347717781,
  -0.19027917801382827],
 [2.2156083550653216,
  -1.601602647737431,
  0.9489340585673027,
  0.25853525659863774],
 [1.262733035120141,
  0.4647171715451077,
  0.7855240412916846,
  0.10288419746291633],
 [0.41656086050376323,
  0.5360584514829704,
  1.0912726574360267,
  0.9282245562999204],
 [-0.6109514781845994,
  -0.7870312093729754,
  0.4089589858869726,
  -0.19951760561737347],
 [0.590151248129295,
  -0.8705893875161342,
  0.7138247490645632,
  0.26213709695390236],
 [-1.755666438649974,
  1.1360487788791098,
  -0.501866757178234,
  -0.19447697620627652],
 [-0.7281492833425428,
  0.8570576642711266,
  -0.516205291770271,
  -0.8986997751532374],
 [0.37951336410284486,
  -0.5836144813056405,
  -1.339199949229909,
  1.7655057186894647],
 [-0.11924664011057036,
  -0.8151836173831355,
  0.15953592083224863,
  0.5997210768101574],
 [-1.0344000404835287,
  -0.1927325939172742,
  0.4711382012276668,
  -1.0177247087960832],
 [0.21191530266515096,
  0.9760008646728741,
  1.7966393869167625,
  -0.9638616547069297],
 [-0.5216922752763852,
  0.05072452652524248,
  0.6538066965844366,
  0.3941082783849686],
 [-0.6128446120990898,
  1.0638704136871533,
  -0.3474354403758688,
  -0.5600506615194955],
 [0.0314832486085949,
  0.6333309477287994,
  -0.1410672347962927,
  -0.3527117061856068],
 [-0.8984445850118237,
  -0.0891353955835292,
  0.9347746534976368,
  1.5870276368510332],
 [1.1547095564025947,
  -0.9750423629130147,
  0.7315388818547447,
  0.39842667430090495],
 [-0.026228692215669622,
  -0.9129611519024567,
  0.3641417141534963,
  0.8778737609140921],
 [0.12890159181174998,
  0.5879216401009915,
  -0.02414852650382752,
  0.8467565364357783],
 [0.5679963801515069,
  1.3346489992225792,
  1.5087099200582526,
  -1.43462039782913],
 [-0.16994171374740272,
  1.5049834086910496,
  -0.43258999116796387,
  -0.19729623012336267],
 [0.9231985089997424,
  -0.7452396259905097,
  0.3065291696904738,
  -1.2409454933308648],
 [-0.7394150145693172,
  -0.11318352949975279,
  -0.5744131351657189,
  0.4626196845813334],
 [-0.7455686261465849,
  1.501140165992657,
  0.13702516086842229,
  0.14584426599630326],
 [2.7462078893895914,
  0.0232160613270955,
  0.6893470711382276,
  0.06271219759922103],
 [0.22217328235388048,
  -2.159725153039193,
  1.1247271468164848,
  1.7553789196449952],
 [0.617089087438798,
  -0.505809780296872,
  0.24787675153302477,
  -0.42755182844006534],
 [0.3486656650891123,
  -2.174779513735796,
  -0.3860141940046892,
  -0.5190346072928094],
 [0.8716974882094033,
  0.3266917715154943,
  -1.2728440887521089,
  0.03154576912527856],
 [0.42329294454847516,
  -0.7366694861334999,
  0.43242897801710267,
  1.2785872645639191],
 [-0.922575561390157,
  -1.1390598973585486,
  -0.42191824892667534,
  0.5394142056343331],
 [-1.7814041154288471,
  -1.347488123539453,
  0.5222514995468601,
  -0.41320233176664056],
 [-0.7037834096559682,
  0.883054210311981,
  -1.2161737656315543,
  0.31339353977957274],
 [2.593097639553493,
  0.615973698131076,
  -0.9059177538420238,
  0.20319397697257552],
 [-0.029688348039895264,
  -0.4643089592984803,
  -0.6326266955749361,
  -0.5940804651669777],
 [-0.815693206611333,
  0.2430627626559982,
  -0.8297334344471459,
  -1.0810886479578707],
 [-0.4905050830938787,
  0.9110950629210999,
  0.3358640639913778,
  -1.2613593659803572],
 [-0.3104072579833824,
  0.27026973397089277,
  0.8321702973416797,
  -2.1311714684467757],
 [1.254003730739229,
  0.28669139766315027,
  -0.9932954613131278,
  0.6105617881128865],
 [-0.9310620325222373,
  0.6944585178520851,
  -0.02071668622591229,
  -2.314566865172928],
 [-0.7696611645227921,
  1.4805490376158403,
  -2.5550990211983167,
  -0.22735900367809506],
 [0.16597208865465224,
  0.07307642256029055,
  2.3242188269161983,
  -1.1883923684575586],
 [-1.4941925290949072,
  0.5927559533980807,
  0.5580543167471924,
  1.2316225812774853],
 [-1.1267961987291855,
  -0.5920807543266717,
  -0.7703569582864985,
  -0.029192400216146868],
 [0.7387157174603602,
  -1.6311376912876645,
  1.2030029758360377,
  -1.2585571980489354],
 [-1.657317148509996,
  0.9070420845963935,
  -0.6587817025081513,
  -0.7228513775975987],
 [-0.692938069323166,
  1.4492432503661412,
  0.3630231974910531,
  -0.8420446461836114],
 [0.18700181012462622,
  -0.930114981021689,
  -2.04834375811817,
  -1.0282916562623727],
 [1.452295093347088,
  0.6058919729652751,
  -0.4191322181435486,
  0.019365025119118206],
 [0.5369141192374356,
  -0.45907525535911936,
  0.16379690630257035,
  0.47677847438703097],
 [0.6403604103066525,
  -1.1168117435928144,
  1.710846843572386,
  0.3855840649574592],
 [-0.014749303945088086,
  0.587664898576715,
  -0.7310243193247294,
  -0.5975124280780953],
 [1.5984408562452077,
  -0.8776354625879542,
  0.3381001756253141,
  -1.0225976353566009],
 [0.24375563730229113,
  -0.2996417322186964,
  -0.2843583434989864,
  0.9750122067474959],
 [-0.8329645429633309,
  -1.7791973417146414,
  -0.7022929366028051,
  -0.6083663157264295],
 [-0.2385314854152608,
  -0.1157834525005217,
  -0.2182723283537997,
  -1.7213766263160688],
 [-0.01031823106061962,
  0.207033671673153,
  -1.415439767861788,
  -1.3191575049635957],
 [0.8117188050789386,
  -2.22269780623392,
  0.09103438210999253,
  0.21043994189327236],
 [-0.7340860726247853,
  2.715991531095195,
  2.407980958345234,
  -1.005152219007953],
 [1.9925081316431983,
  -0.47134203638325395,
  -0.15564515773871285,
  0.3008631066441532],
 [0.48779815877210597,
  -0.13647597032571748,
  -0.07915483601422033,
  -0.4392066674094011],
 [-0.4164586350233964,
  1.3235332636870005,
  -0.129529244416776,
  -0.22692300170334992],
 [-0.5345062923293004,
  0.10685551529479347,
  -0.4659047346698115,
  0.6276067678592547],
 [-0.4494254935982989,
  0.49057372110790115,
  -0.9093733753998007,
  0.8375840188129009],
 [0.16172744690807483,
  0.5208807866939226,
  -1.6790890771628524,
  -0.7228679814028323],
 [0.519210126662611,
  0.7761054647209813,
  -1.0898831907277826,
  0.7759771164442313],
 [0.5140572005278204,
  0.0599581659473516,
  0.5299169695956866,
  -0.6794772313881757],
 [-0.5245280620444306,
  -0.3188489599849237,
  0.3464939618714814,
  -1.0479463215623512],
 [0.7731895669712536,
  1.4587019139599855,
  0.0777645923685736,
  0.6795909860871822],
 [-0.9616022949411445,
  -0.9407936863082517,
  0.4016313035840488,
  0.6212990696892555],
 [0.41828629685520885,
  -2.4126806748774237,
  0.8692387548538689,
  -0.6394079441208799],
 [-0.8828585536136373,
  -1.463536750460856,
  0.8306674836145024,
  -1.3165531249425961],
 [0.23879897819311577,
  0.7001142470799144,
  1.8914979676238284,
  0.8323875687725351],
 [-1.7834111208337031,
  -1.7657757190643588,
  1.6293533876341757,
  1.0461179776167198],
 [-0.8903224369138403,
  0.1533761356897366,
  0.5769341918718134,
  0.25657852575213896],
 [-0.16207300569103647,
  0.6608540303042868,
  -0.14506548041982936,
  0.5328912986293775],
 [-2.2360268708464446,
  -0.04945454203419249,
  1.1613860490285104,
  -0.3617611687065853],
 [0.13200031772573928,
  1.7604064361477902,
  0.31733165376267874,
  -0.22987102391239708],
 [-0.9097437823186676,
  -1.320591543433901,
  0.2679176493587466,
  -2.097994154090361],
 [0.4468375931116211,
  0.7919402699155988,
  0.6153451357269255,
  2.1298437209416883],
 [-1.1893458036833886,
  0.7692408998533611,
  -0.7673214661412425,
  0.49397348924213524],
 [0.1402497547049889,
  -0.27023699739724844,
  0.02598032356302068,
  0.5677919345838803],
 [-1.7823365486878922,
  -0.6771217949005579,
  0.8322320656102203,
  1.0366803978428512],
 [-1.4958316174785167,
  -0.5611299955539607,
  -0.7642281799690779,
  1.7319854688134393],
 [1.0500472751733496,
  0.5330223278347807,

Обратите внимание, что эта операция может занять много времени, если ваш `DataFrame` имеет столбцы с разными типами данных, что сводится к фундаментальному различию между pandas и `NumPy`: массивы `NumPy` имеют один тип данных для всего массива, тогда как `DataFrames` в pandas имеет один тип данных для каждого столбца. Когда вы вызываете `DataFrame.to_numpy()`, pandas определит тип данных `NumPy`, который может содержать все типы данных `DataFrame`. Этот тип данных может в конечном итоге оказаться объектом (`object`, т.е. строкой), что потребует приведения каждого значения к объекту Python.

Наш `DataFrame` содержит значения с плавающей точкой, поэтому `DataFrame.to_numpy()` сработает быстро и не требует копирования данных.

Для df2, который содержит несколько типов данных, вызов `DataFrame.to_numpy()` является относительно дорогостоящим:

In [48]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'red', 'foobar'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'green', 'foobar'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'blue', 'foobar'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'red', 'foobar']],
      dtype=object)

Транспонируем данные:

In [49]:
df_copy = df.T

In [50]:
df_copy

,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,...,2061-03-31,2061-04-30,2061-05-31,2061-06-30,2061-07-31,2061-08-31,2061-09-30,2061-10-31,2061-11-30,2061-12-31
A,-0.311412,0.248808,0.804578,0.476569,-0.001478,1.585082,0.606025,-1.783629,0.469248,0.575168,...,1.760953,0.091172,-2.060853,0.270393,0.268553,0.314799,-2.012953,-1.242894,-1.192910,0.878295
B,0.667208,0.044664,-0.081503,-1.458649,-0.996307,0.067398,0.288407,-0.692394,-1.174504,-0.337926,...,1.026578,-0.633736,-0.316440,-1.469325,-0.601572,-0.082635,0.601205,-1.331563,0.329820,-0.039897
C,1.717706,0.625272,0.553259,-1.171720,0.367370,0.149100,0.004997,-1.253129,0.198428,0.378607,...,1.879497,-0.745920,-0.324916,1.197017,-2.080317,-0.249399,-1.177553,-0.762655,-0.181624,0.869247
D,-1.847369,1.730853,-0.262377,-1.773515,0.140001,1.236530,1.208718,0.472508,-0.308379,1.549686,...,0.570918,-0.659835,1.397315,0.587816,-0.779178,1.087080,1.591242,0.825453,-0.949195,0.218944

In [51]:
df_copy

,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,...,2061-03-31,2061-04-30,2061-05-31,2061-06-30,2061-07-31,2061-08-31,2061-09-30,2061-10-31,2061-11-30,2061-12-31
A,-0.311412,0.248808,0.804578,0.476569,-0.001478,1.585082,0.606025,-1.783629,0.469248,0.575168,...,1.760953,0.091172,-2.060853,0.270393,0.268553,0.314799,-2.012953,-1.242894,-1.192910,0.878295
B,0.667208,0.044664,-0.081503,-1.458649,-0.996307,0.067398,0.288407,-0.692394,-1.174504,-0.337926,...,1.026578,-0.633736,-0.316440,-1.469325,-0.601572,-0.082635,0.601205,-1.331563,0.329820,-0.039897
C,1.717706,0.625272,0.553259,-1.171720,0.367370,0.149100,0.004997,-1.253129,0.198428,0.378607,...,1.879497,-0.745920,-0.324916,1.197017,-2.080317,-0.249399,-1.177553,-0.762655,-0.181624,0.869247
D,-1.847369,1.730853,-0.262377,-1.773515,0.140001,1.236530,1.208718,0.472508,-0.308379,1.549686,...,0.570918,-0.659835,1.397315,0.587816,-0.779178,1.087080,1.591242,0.825453,-0.949195,0.218944

Сортировка по столбцам, см. [`sort_index()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_index.html):

In [52]:
df.sort_index(axis=0, ascending=False) # по умолчанию axis=0, т.е. сортировка по строкам

                   A         B         C         D
2061-12-31  0.878295 -0.039897  0.869247  0.218944
2061-11-30 -1.192910  0.329820 -0.181624 -0.949195
2061-10-31 -1.242894 -1.331563 -0.762655  0.825453
2061-09-30 -2.012953  0.601205 -1.177553  1.591242
2061-08-31  0.314799 -0.082635 -0.249399  1.087080
...              ...       ...       ...       ...
2012-05-31 -0.001478 -0.996307  0.367370  0.140001
2012-04-30  0.476569 -1.458649 -1.171720 -1.773515
2012-03-31  0.804578 -0.081503  0.553259 -0.262377
2012-02-29  0.248808  0.044664  0.625272  1.730853
2012-01-31 -0.311412  0.667208  1.717706 -1.847369

[600 rows x 4 columns]

Сортировка по значениям, см. [`sort_values()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values):

In [53]:
df.sort_values(by=['A','C']) # по умолчанию сортировка по индексу, выбрали столбец 'B'

                   A         B         C         D
2017-12-31 -3.886403 -1.466020 -0.022690  0.593622
2043-09-30 -2.826097 -0.772263  0.308189 -0.275274
2042-10-31 -2.642154 -1.231598  1.137054 -0.240391
2037-04-30 -2.527121  0.672354 -1.507424  0.306174
2029-07-31 -2.236027 -0.049455  1.161386 -0.361761
...              ...       ...       ...       ...
2013-10-31  2.439012 -2.041659 -0.169398  1.065935
2025-12-31  2.593098  0.615974 -0.905918  0.203194
2050-06-30  2.735801 -1.415964 -0.199138 -0.201553
2025-03-31  2.746208  0.023216  0.689347  0.062712
2048-02-29  3.106999 -0.525790 -0.998607 -1.610760

[600 rows x 4 columns]

## Выбор элементов

Рекомендуем использовать оптимизированные методы pandas для доступа к данным:  `.ix`, `.loc` и `.iloc`.

### Получение

Выбор столбца, который возвращает [`Series`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html#pandas.Series), эквивалентно `df.A`:

In [54]:
df['A']

2012-01-31   -0.311412
2012-02-29    0.248808
2012-03-31    0.804578
2012-04-30    0.476569
2012-05-31   -0.001478
                ...
2061-08-31    0.314799
2061-09-30   -2.012953
2061-10-31   -1.242894
2061-11-30   -1.192910
2061-12-31    0.878295
Freq: ME, Name: A, Length: 600, dtype: float64

Выбор с помощью `[ ]`, вырезает строки:

In [55]:
df[:'2013-04-30']

                   A         B         C         D
2012-01-31 -0.311412  0.667208  1.717706 -1.847369
2012-02-29  0.248808  0.044664  0.625272  1.730853
2012-03-31  0.804578 -0.081503  0.553259 -0.262377
2012-04-30  0.476569 -1.458649 -1.171720 -1.773515
2012-05-31 -0.001478 -0.996307  0.367370  0.140001
2012-06-30  1.585082  0.067398  0.149100  1.236530
2012-07-31  0.606025  0.288407  0.004997  1.208718
2012-08-31 -1.783629 -0.692394 -1.253129  0.472508
2012-09-30  0.469248 -1.174504  0.198428 -0.308379
2012-10-31  0.575168 -0.337926  0.378607  1.549686
2012-11-30 -0.257932 -1.869790  0.075635 -0.810716
2012-12-31 -0.706510 -0.068075  2.874875  0.284778
2013-01-31  0.062229 -0.898127 -0.051427  1.077788
2013-02-28  0.152341 -0.400381 -1.287939  0.213011
2013-03-31  1.757002  0.932732  0.366139  1.903312
2013-04-30 -1.161609 -0.689216 -0.691394 -0.968044

In [56]:
df['2013-01-02':'2013-02-03']

                   A         B         C         D
2013-01-31  0.062229 -0.898127 -0.051427  1.077788

### Выбор по метке

Подробнее см. в [Документации](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-label)

Для получения строки с помощью метки:

In [57]:
df.loc['2013-11-30','A'] # метка индекса Timestamp('2013-01-01 00:00:00', freq='D')

np.float64(-0.5147734294564702)

In [61]:
df.loc['2013-11-30','A'] = 10.30 # переприсваивание объекта к срезу

In [62]:
df.loc['2013-11-30','A']

np.float64(10.3)

In [65]:
df[df['A'] == np.float64(10.3)] # ячейка поменяла значения (не делать, если не необходимо)

               A         B        C         D
2013-11-30  10.3 -1.057012 -0.23714  1.216853

Выбор по нескольким осям:

In [58]:
df.loc['2013-11-30', ['A', 'B']]

A   -0.514773
B   -1.057012
Name: 2013-11-30 00:00:00, dtype: float64

При отображении срезов меток включаются обе конечные точки:

In [59]:
df.loc['2013-01-02':'2014-01-04', ['C', 'B']]

                   C         B
2013-01-31 -0.051427 -0.898127
2013-02-28 -1.287939 -0.400381
2013-03-31  0.366139  0.932732
2013-04-30 -0.691394 -0.689216
2013-05-31  0.477091  0.842597
2013-06-30  1.355888 -1.369857
2013-07-31 -0.486616 -1.731272
2013-08-31  0.965656  1.520072
2013-09-30 -0.825309 -0.899919
2013-10-31 -0.169398 -2.041659
2013-11-30 -0.237140 -1.057012
2013-12-31  0.900067 -0.547614

Для получения скалярного значения:

In [60]:
df.at[dates[3], 'A'] #одиночное значение по индексу

np.float64(0.47656882150960644)

### Выбор по позиции

Подробнее см. в [Документации](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-integer)

Выбор позиции с помощью целых чисел:

In [66]:
df

                   A         B         C         D
2012-01-31 -0.311412  0.667208  1.717706 -1.847369
2012-02-29  0.248808  0.044664  0.625272  1.730853
2012-03-31  0.804578 -0.081503  0.553259 -0.262377
2012-04-30  0.476569 -1.458649 -1.171720 -1.773515
2012-05-31 -0.001478 -0.996307  0.367370  0.140001
...              ...       ...       ...       ...
2061-08-31  0.314799 -0.082635 -0.249399  1.087080
2061-09-30 -2.012953  0.601205 -1.177553  1.591242
2061-10-31 -1.242894 -1.331563 -0.762655  0.825453
2061-11-30 -1.192910  0.329820 -0.181624 -0.949195
2061-12-31  0.878295 -0.039897  0.869247  0.218944

[600 rows x 4 columns]

In [67]:
df.iloc[1]

A    0.248808
B    0.044664
C    0.625272
D    1.730853
Name: 2012-02-29 00:00:00, dtype: float64

По целочисленным срезам, действующим аналогично NumPy / Python, т.е. правое граничное значение не включается:

In [68]:
df.iloc[3:5, 0:2]

                   A         B
2012-04-30  0.476569 -1.458649
2012-05-31 -0.001478 -0.996307

По спискам целочисленных позиций, аналогично стилю NumPy / Python:

In [69]:
df.iloc[[1, 2, 4], [0, 2]]

                   A         C
2012-02-29  0.248808  0.625272
2012-03-31  0.804578  0.553259
2012-05-31 -0.001478  0.367370

Для явного создания среза строк:

In [70]:
df.iloc[1:3, :]

                   A         B         C         D
2012-02-29  0.248808  0.044664  0.625272  1.730853
2012-03-31  0.804578 -0.081503  0.553259 -0.262377

Для явного создания среза столбцов:

In [71]:
df.iloc[:, 1:3]

                   B         C
2012-01-31  0.667208  1.717706
2012-02-29  0.044664  0.625272
2012-03-31 -0.081503  0.553259
2012-04-30 -1.458649 -1.171720
2012-05-31 -0.996307  0.367370
...              ...       ...
2061-08-31 -0.082635 -0.249399
2061-09-30  0.601205 -1.177553
2061-10-31 -1.331563 -0.762655
2061-11-30  0.329820 -0.181624
2061-12-31 -0.039897  0.869247

[600 rows x 2 columns]

Для явного получения значений:

In [72]:
df.iloc[1, 1]

np.float64(0.04466423042135691)

Для получения быстрого доступа к скаляру (эквивалентно предыдущему методу):

In [73]:
df.iat[1, 1]

np.float64(0.04466423042135691)

### Булево индексирование

Использование значений столбца для выбора данных:

In [74]:
df[(df['A'] > 0) | (df['B'] > 0) & ( df['C'] < 0)]

                   A         B         C         D
2012-02-29  0.248808  0.044664  0.625272  1.730853
2012-03-31  0.804578 -0.081503  0.553259 -0.262377
2012-04-30  0.476569 -1.458649 -1.171720 -1.773515
2012-06-30  1.585082  0.067398  0.149100  1.236530
2012-07-31  0.606025  0.288407  0.004997  1.208718
...              ...       ...       ...       ...
2061-07-31  0.268553 -0.601572 -2.080317 -0.779178
2061-08-31  0.314799 -0.082635 -0.249399  1.087080
2061-09-30 -2.012953  0.601205 -1.177553  1.591242
2061-11-30 -1.192910  0.329820 -0.181624 -0.949195
2061-12-31  0.878295 -0.039897  0.869247  0.218944

[389 rows x 4 columns]

Выбор значений из `DataFrame`, для которых выполняется логическое условие:

In [75]:
df[df > 0]

                   A         B         C         D
2012-01-31       NaN  0.667208  1.717706       NaN
2012-02-29  0.248808  0.044664  0.625272  1.730853
2012-03-31  0.804578       NaN  0.553259       NaN
2012-04-30  0.476569       NaN       NaN       NaN
2012-05-31       NaN       NaN  0.367370  0.140001
...              ...       ...       ...       ...
2061-08-31  0.314799       NaN       NaN  1.087080
2061-09-30       NaN  0.601205       NaN  1.591242
2061-10-31       NaN       NaN       NaN  0.825453
2061-11-30       NaN  0.329820       NaN       NaN
2061-12-31  0.878295       NaN  0.869247  0.218944

[600 rows x 4 columns]

Использование метода [`isin()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html#pandas.Series.isin) для фильтрации:

In [76]:
df2

     A          B    C  D      E       F
0  1.0 2013-01-02  1.0  3    red  foobar
1  1.0 2013-01-02  1.0  3  green  foobar
2  1.0 2013-01-02  1.0  3   blue  foobar
3  1.0 2013-01-02  1.0  3    red  foobar

In [78]:
df2['E'].isin(['green', 'blue'])

0    False
1     True
2     True
3    False
Name: E, dtype: bool

In [79]:
~df2['E'].isin(['green', 'blue'])

0     True
1    False
2    False
3     True
Name: E, dtype: bool

In [80]:
df2[~df2['E'].isin(['green', 'blue'])] # фильтруем

     A          B    C  D    E       F
0  1.0 2013-01-02  1.0  3  red  foobar
3  1.0 2013-01-02  1.0  3  red  foobar

## Изменение / добавление значений

In [ ]:
df['E'] = ['one', 'one', 'two', 'three', 'four', 'three']*100 # добавляем столбец
df

                   A         B         C         D      E
2013-01-31 -2.065810  0.500734  0.363846  0.066299    one
2013-02-28  0.348288 -1.535217 -0.211007 -0.091686    one
2013-03-31  0.508579 -1.424744  1.767825  1.360248    two
2013-04-30 -0.576584 -0.529803  0.251141  0.094734  three
2013-05-31  0.192248  1.020445  0.812392  0.351854   four
...              ...       ...       ...       ...    ...
2062-08-31 -0.922229  2.214785  1.755481 -1.343570    one
2062-09-30 -0.353849 -0.170232  0.114496  0.495401    two
2062-10-31 -2.533816 -0.057073  0.021984 -0.759623  three
2062-11-30  2.399247 -0.729486 -0.135819 -1.375543   four
2062-12-31  0.635386 -0.249315  0.981285 -1.633425  three

[600 rows x 5 columns]

При добавлении нового столбца данные автоматически выравниваются по индексам:

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20130228', periods=6,freq='M'))
s1

2013-02-28    1
2013-03-31    2
2013-04-30    3
2013-05-31    4
2013-06-30    5
2013-07-31    6
Freq: M, dtype: int64

In [ ]:
df['F'] = s1 # отсутствующие значения после выравнивания заменились NaN
df

                   A         B         C         D      E    F
2013-01-31 -2.065810  0.500734  0.363846  0.066299    one  NaN
2013-02-28  0.348288 -1.535217 -0.211007 -0.091686    one  1.0
2013-03-31  0.508579 -1.424744  1.767825  1.360248    two  2.0
2013-04-30 -0.576584 -0.529803  0.251141  0.094734  three  3.0
2013-05-31  0.192248  1.020445  0.812392  0.351854   four  4.0
...              ...       ...       ...       ...    ...  ...
2062-08-31 -0.922229  2.214785  1.755481 -1.343570    one  NaN
2062-09-30 -0.353849 -0.170232  0.114496  0.495401    two  NaN
2062-10-31 -2.533816 -0.057073  0.021984 -0.759623  three  NaN
2062-11-30  2.399247 -0.729486 -0.135819 -1.375543   four  NaN
2062-12-31  0.635386 -0.249315  0.981285 -1.633425  three  NaN

[600 rows x 6 columns]

Установка значений по метке:

In [ ]:
df.iat[0, 1] = 0
df

                   A         B         C         D      E    F
2013-01-31 -2.065810  0.000000  0.363846  0.066299    one  NaN
2013-02-28  0.348288 -1.535217 -0.211007 -0.091686    one  1.0
2013-03-31  0.508579 -1.424744  1.767825  1.360248    two  2.0
2013-04-30 -0.576584 -0.529803  0.251141  0.094734  three  3.0
2013-05-31  0.192248  1.020445  0.812392  0.351854   four  4.0
...              ...       ...       ...       ...    ...  ...
2062-08-31 -0.922229  2.214785  1.755481 -1.343570    one  NaN
2062-09-30 -0.353849 -0.170232  0.114496  0.495401    two  NaN
2062-10-31 -2.533816 -0.057073  0.021984 -0.759623  three  NaN
2062-11-30  2.399247 -0.729486 -0.135819 -1.375543   four  NaN
2062-12-31  0.635386 -0.249315  0.981285 -1.633425  three  NaN

[600 rows x 6 columns]

In [ ]:
df.loc['2013-01-31', 'D'] = 111
df

                   A         B         C           D      E    F
2013-01-31 -2.065810  0.000000  0.363846  111.000000    one  NaN
2013-02-28  0.348288 -1.535217 -0.211007   -0.091686    one  1.0
2013-03-31  0.508579 -1.424744  1.767825    1.360248    two  2.0
2013-04-30 -0.576584 -0.529803  0.251141    0.094734  three  3.0
2013-05-31  0.192248  1.020445  0.812392    0.351854   four  4.0
...              ...       ...       ...         ...    ...  ...
2062-08-31 -0.922229  2.214785  1.755481   -1.343570    one  NaN
2062-09-30 -0.353849 -0.170232  0.114496    0.495401    two  NaN
2062-10-31 -2.533816 -0.057073  0.021984   -0.759623  three  NaN
2062-11-30  2.399247 -0.729486 -0.135819   -1.375543   four  NaN
2062-12-31  0.635386 -0.249315  0.981285   -1.633425  three  NaN

[600 rows x 6 columns]

Установка значений путем присвоения массива NumPy:

In [ ]:
df['G'] = np.array([5] * len(df))
df

                   A         B         C           D      E    F  G
2013-01-31 -2.065810  0.000000  0.363846  111.000000    one  NaN  5
2013-02-28  0.348288 -1.535217 -0.211007   -0.091686    one  1.0  5
2013-03-31  0.508579 -1.424744  1.767825    1.360248    two  2.0  5
2013-04-30 -0.576584 -0.529803  0.251141    0.094734  three  3.0  5
2013-05-31  0.192248  1.020445  0.812392    0.351854   four  4.0  5
...              ...       ...       ...         ...    ...  ... ..
2062-08-31 -0.922229  2.214785  1.755481   -1.343570    one  NaN  5
2062-09-30 -0.353849 -0.170232  0.114496    0.495401    two  NaN  5
2062-10-31 -2.533816 -0.057073  0.021984   -0.759623  three  NaN  5
2062-11-30  2.399247 -0.729486 -0.135819   -1.375543   four  NaN  5
2062-12-31  0.635386 -0.249315  0.981285   -1.633425  three  NaN  5

[600 rows x 7 columns]

In [ ]:
df_numeric = df._get_numeric_data()
df_numeric[df_numeric > 0] = -df_numeric # все положительные превращаем в отрицательные
df_numeric

                   A         B         C           D    F  G
2013-01-31 -2.065810  0.000000 -0.363846 -111.000000  NaN -5
2013-02-28 -0.348288 -1.535217 -0.211007   -0.091686 -1.0 -5
2013-03-31 -0.508579 -1.424744 -1.767825   -1.360248 -2.0 -5
2013-04-30 -0.576584 -0.529803 -0.251141   -0.094734 -3.0 -5
2013-05-31 -0.192248 -1.020445 -0.812392   -0.351854 -4.0 -5
...              ...       ...       ...         ...  ... ..
2062-08-31 -0.922229 -2.214785 -1.755481   -1.343570  NaN -5
2062-09-30 -0.353849 -0.170232 -0.114496   -0.495401  NaN -5
2062-10-31 -2.533816 -0.057073 -0.021984   -0.759623  NaN -5
2062-11-30 -2.399247 -0.729486 -0.135819   -1.375543  NaN -5
2062-12-31 -0.635386 -0.249315 -0.981285   -1.633425  NaN -5

[600 rows x 6 columns]

In [ ]:
np.sin(df_numeric)

                   A         B         C         D         F         G
2013-01-31 -0.879962  0.000000 -0.355871  0.864551       NaN  0.958924
2013-02-28 -0.341289 -0.999367 -0.209444 -0.091558 -0.841471  0.958924
2013-03-31 -0.486937 -0.989353 -0.980653 -0.977916 -0.909297  0.958924
2013-04-30 -0.545163 -0.505364 -0.248509 -0.094592 -0.141120  0.958924
2013-05-31 -0.191066 -0.852341 -0.725934 -0.344638  0.756802  0.958924
...              ...       ...       ...       ...       ...       ...
2062-08-31 -0.796950 -0.799707 -0.982994 -0.974295       NaN  0.958924
2062-09-30 -0.346511 -0.169411 -0.114246 -0.475385       NaN  0.958924
2062-10-31 -0.571044 -0.057042 -0.021982 -0.688648       NaN  0.958924
2062-11-30 -0.676018 -0.666487 -0.135402 -0.980999       NaN  0.958924
2062-12-31 -0.593488 -0.246740 -0.831213 -0.998039       NaN  0.958924

[600 rows x 6 columns]

### Применение функций к данным (apply)

Метод apply() — это инструмент для преобразования объекта DataFrame, его можно применять как к одному столбцу, так и к нескольким.

In [ ]:
# Функция numpy.cumsum() возвращает кумулятивную сумму элементов по заданной оси
df[['A', 'B']].apply(np.cumsum)

                     A           B
2013-01-31   -2.065810    0.000000
2013-02-28   -2.414098   -1.535217
2013-03-31   -2.922677   -2.959962
2013-04-30   -3.499261   -3.489765
2013-05-31   -3.691509   -4.510210
...                ...         ...
2062-08-31 -505.031380 -452.881064
2062-09-30 -505.385229 -453.051296
2062-10-31 -507.919045 -453.108369
2062-11-30 -510.318292 -453.837855
2062-12-31 -510.953678 -454.087170

[600 rows x 2 columns]

Можно применить лямбда-функции, которые полезны в том случае, когда нужна одноразовая функция. Такие функции еще называют анонимными.

`lambda arguments: expression`

In [ ]:
df_numeric.apply(lambda x: x.max() - x.min())

A      3.165183
B      2.845246
C      3.461340
D    110.999821
F      5.000000
G      0.000000
dtype: float64

### Строковые методы

Series оснащен набором методов в атрибуте `str` для обработки строк, которые упрощают работу с каждым элементом массива, подробнее см. в [Документации](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html#text-string-methods).

In [ ]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s

0       A
1       B
2       C
3    Aaba
4    Baca
5     NaN
6    CABA
7     dog
8     cat
dtype: object

In [ ]:
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [ ]:
s.str.upper()

0       A
1       B
2       C
3    AABA
4    BACA
5     NaN
6    CABA
7     DOG
8     CAT
dtype: object

## Обработка пропусков в данных

pandas в основном использует значение [`np.nan`](https://numpy.org/doc/stable/user/misc.html) для представления отсутствующих данных. По умолчанию они не включается в вычисления, см. подробнее в [Документации](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#missing-data)

### Обнаружение пропусков

Метод `info()` соотносит максимальное количество записей в датафрейме с количеством записей в каждом столбце:

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 600 entries, 2013-01-31 to 2062-12-31
Freq: M
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       600 non-null    float64
 1   B       600 non-null    float64
 2   C       600 non-null    float64
 3   D       600 non-null    float64
 4   E       600 non-null    object
 5   F       6 non-null      float64
 6   G       600 non-null    int64
dtypes: float64(5), int64(1), object(1)
memory usage: 53.7+ KB

Можно последовательно использовать методы `isna()` и `sum()`:

In [ ]:
# .isna() выдает True или 1, если есть пропуск, .sum() суммирует единицы по столбцам
df.isna().sum()

A      0
B      0
C      0
D      0
E      0
F    594
G      0
dtype: int64

Также не сложно посчитать процент пропущенных значений:

In [ ]:
# для этого разделим сумму пропусков в каждом столбце на количество наблюдений,
# округлим результат и умножим его на 100
df.isna().sum() / len(df.round(4)) * 100

A     0.0
B     0.0
C     0.0
D     0.0
E     0.0
F    99.0
G     0.0
dtype: float64

### Удаление пропусков

Чтобы удалить строки, в которых отсутствуют данные, см. [`dropna()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html):

In [ ]:
df.dropna() # how='any', axis=0 по умолчанию, т.е. удаляются все строки с пропущенными данными

                   A         B         C         D      E    F  G
2013-02-28 -0.348288 -1.535217 -0.211007 -0.091686    one -1.0 -5
2013-03-31 -0.508579 -1.424744 -1.767825 -1.360248    two -2.0 -5
2013-04-30 -0.576584 -0.529803 -0.251141 -0.094734  three -3.0 -5
2013-05-31 -0.192248 -1.020445 -0.812392 -0.351854   four -4.0 -5
2013-06-30 -1.509585 -0.730217 -0.730922 -0.148052  three -5.0 -5
2013-07-31 -0.928314 -1.522277 -0.608694 -0.389239    one -6.0 -5

Если в одном из столбцов большой процент пропусков, построчное удаление просто оставит нас без данных. В этом случае, если мы выбираем стратегию удаления данных, разумнее удалить сам столбец.

In [ ]:
# передадим в параметр columns тот столбец, который хотим удалить
df.drop(columns = ['F'])

                   A         B         C           D      E  G
2013-01-31 -2.065810  0.000000 -0.363846 -111.000000    one -5
2013-02-28 -0.348288 -1.535217 -0.211007   -0.091686    one -5
2013-03-31 -0.508579 -1.424744 -1.767825   -1.360248    two -5
2013-04-30 -0.576584 -0.529803 -0.251141   -0.094734  three -5
2013-05-31 -0.192248 -1.020445 -0.812392   -0.351854   four -5
...              ...       ...       ...         ...    ... ..
2062-08-31 -0.922229 -2.214785 -1.755481   -1.343570    one -5
2062-09-30 -0.353849 -0.170232 -0.114496   -0.495401    two -5
2062-10-31 -2.533816 -0.057073 -0.021984   -0.759623  three -5
2062-11-30 -2.399247 -0.729486 -0.135819   -1.375543   four -5
2062-12-31 -0.635386 -0.249315 -0.981285   -1.633425  three -5

[600 rows x 6 columns]

### Заполнение пропусков

Пропуски в числовых признаках можно заполнить средним арифметическим или медианой:

In [ ]:
df.head(10)

                   A         B         C           D      E    F  G
2013-01-31 -2.065810  0.000000 -0.363846 -111.000000    one  NaN -5
2013-02-28 -0.348288 -1.535217 -0.211007   -0.091686    one -1.0 -5
2013-03-31 -0.508579 -1.424744 -1.767825   -1.360248    two -2.0 -5
2013-04-30 -0.576584 -0.529803 -0.251141   -0.094734  three -3.0 -5
2013-05-31 -0.192248 -1.020445 -0.812392   -0.351854   four -4.0 -5
2013-06-30 -1.509585 -0.730217 -0.730922   -0.148052  three -5.0 -5
2013-07-31 -0.928314 -1.522277 -0.608694   -0.389239    one -6.0 -5
2013-08-31 -0.879384 -1.607191 -1.247258   -0.485029    one  NaN -5
2013-09-30 -0.495681 -0.162004 -0.760876   -0.232103    two  NaN -5
2013-10-31 -0.320099 -0.499259 -0.433996   -1.191528  three  NaN -5

In [ ]:
# сделаем копию датафрейма
fillna_median = df.copy()

# заполним пропуски в столбце F медианным значением,
# можно заполнить и средним арифметическим через метод .mean()
fillna_median.F.fillna(fillna_median.F.median(), inplace = True)

# убедимся, что пропусков не осталось
fillna_median.F.isna().sum()

0

У такого простого и понятного подхода тем не менее есть ряд недостатков:

- когда в данных появляется большое количество одинаковых близких к среднему значений, мы снижаем ценную вариативность в данных;
- кроме того, такое заполнение пропусков может быть некорректно. Например, если заполнить пропуски в столбце «Стаж» средним значением или медианой, молодой сотрудник может получить больший стаж, чем у него есть на самом деле, а сотрудник в возрасте, меньший.

Также популярно заполнение значениями из предшествующей (аргумент method='bfill') либо последующей записи (method='ffill'):

In [ ]:
df.fillna(method='bfill')

                   A         B         C           D      E    F  G
2013-01-31 -2.065810  0.000000 -0.363846 -111.000000    one -1.0 -5
2013-02-28 -0.348288 -1.535217 -0.211007   -0.091686    one -1.0 -5
2013-03-31 -0.508579 -1.424744 -1.767825   -1.360248    two -2.0 -5
2013-04-30 -0.576584 -0.529803 -0.251141   -0.094734  three -3.0 -5
2013-05-31 -0.192248 -1.020445 -0.812392   -0.351854   four -4.0 -5
...              ...       ...       ...         ...    ...  ... ..
2062-08-31 -0.922229 -2.214785 -1.755481   -1.343570    one  NaN -5
2062-09-30 -0.353849 -0.170232 -0.114496   -0.495401    two  NaN -5
2062-10-31 -2.533816 -0.057073 -0.021984   -0.759623  three  NaN -5
2062-11-30 -2.399247 -0.729486 -0.135819   -1.375543   four  NaN -5
2062-12-31 -0.635386 -0.249315 -0.981285   -1.633425  three  NaN -5

[600 rows x 7 columns]

Следует отметить, что для аналогичных действий имеются специальные методы с названиями bfill и ffill:

In [ ]:
df.ffill()

                   A         B         C           D      E    F  G
2013-01-31 -2.065810  0.000000 -0.363846 -111.000000    one  NaN -5
2013-02-28 -0.348288 -1.535217 -0.211007   -0.091686    one -1.0 -5
2013-03-31 -0.508579 -1.424744 -1.767825   -1.360248    two -2.0 -5
2013-04-30 -0.576584 -0.529803 -0.251141   -0.094734  three -3.0 -5
2013-05-31 -0.192248 -1.020445 -0.812392   -0.351854   four -4.0 -5
...              ...       ...       ...         ...    ...  ... ..
2062-08-31 -0.922229 -2.214785 -1.755481   -1.343570    one -6.0 -5
2062-09-30 -0.353849 -0.170232 -0.114496   -0.495401    two -6.0 -5
2062-10-31 -2.533816 -0.057073 -0.021984   -0.759623  three -6.0 -5
2062-11-30 -2.399247 -0.729486 -0.135819   -1.375543   four -6.0 -5
2062-12-31 -0.635386 -0.249315 -0.981285   -1.633425  three -6.0 -5

[600 rows x 7 columns]

## Описательная статистика

Метод [`describe()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe) показывает краткую статистическую сводку для данных:

In [ ]:
df.describe()

                A           B           C           D         F      G
count  600.000000  600.000000  600.000000  600.000000  6.000000  600.0
mean    -0.851589   -0.756812   -0.788894   -1.006383 -3.500000   -5.0
std      0.625234    0.567575    0.584924    4.542093  1.870829    0.0
min     -3.184246   -2.845246   -3.461886 -111.000000 -6.000000   -5.0
25%     -1.184371   -1.089441   -1.139980   -1.219287 -4.750000   -5.0
50%     -0.722379   -0.648769   -0.696077   -0.688548 -3.500000   -5.0
75%     -0.355033   -0.325918   -0.319679   -0.316519 -2.250000   -5.0
max     -0.019063    0.000000   -0.000546   -0.000179 -1.000000   -5.0

Вычисление квантилей (для числовых признаков):

In [ ]:
df_numeric.quantile(.1)

A   -1.778458
B   -1.523740
C   -1.598365
D   -1.702961
F   -5.500000
G   -5.000000
Name: 0.1, dtype: float64

Вычисление медианы (для числовых признаков):

In [ ]:
df_numeric.median()

A   -0.722379
B   -0.648769
C   -0.696077
D   -0.688548
F   -3.500000
G   -5.000000
dtype: float64

Та же операция на другой оси (т.е. по строкам):

In [ ]:
df_numeric.median(axis=1)

2013-01-31   -2.065810
2013-02-28   -0.674144
2013-03-31   -1.596285
2013-04-30   -0.553194
2013-05-31   -0.916419
                ...
2062-08-31   -1.755481
2062-09-30   -0.353849
2062-10-31   -0.759623
2062-11-30   -1.375543
2062-12-31   -0.981285
Freq: M, Length: 600, dtype: float64

Вычисление моды (для категориальных признаков):

In [ ]:
numerical_columns = df_numeric.columns
all_columns = df.columns
cat_columns = list(set(all_columns) - set(numerical_columns))
df[cat_columns].mode()

       E
0    one
1  three

## Объединение таблиц

### Concat

Соединение таблиц вдоль выбранной оси

`pd.concat(objs, axis=0, join='outer', ignore_index=False, copy=True, ...)`

* `objs` &mdash; объединяемые таблицы;
* `axis` : {`0` или `'index'`, `1` или `'columns'`} &mdash; ось индексов или ось колонок, иными словами соединение по вертикали или по горизонтали;
* `join` : {`'inner'`, `'outer'`} &mdash; тип объединения &mdash; пересечение или объединение индексов/колонок;
* `ignore_index` &mdash; сохранить индексы или определить и как $0, ..., n-1$;
* `copy` &mdash; копировать данные или нет.

In [81]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])
print('df1:\n', df1)
df2 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                   columns=['letter', 'number', 'animal'])
print('df2:\n', df2)
pd.concat([df1, df2])
# pd.concat([df1, df2], ignore_index=True)

df1:
   letter  number
0      a       1
1      b       2
df2:
   letter  number animal
0      c       3    cat
1      d       4    dog

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

### Merge

Слияние таблиц по вертикали путем выполнения операций слияния баз данных в стиле SQL.

`pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, suffixes=('_x', '_y'), ...)`

In [82]:
# В обеих таблицах ключи повторяются

left = pd.DataFrame({'key': ['A', 'A'],
                     'lval': [1, 2]})
right = pd.DataFrame({'key': ['A', 'A'],
                      'rval': [4, 5]})

In [83]:
left

  key  lval
0   A     1
1   A     2

In [84]:
right

  key  rval
0   A     4
1   A     5

In [85]:
pd.merge(left, right, on='key')

  key  lval  rval
0   A     1     4
1   A     1     5
2   A     2     4
3   A     2     5

В результате объединения получаем 4 строки &mdash; для каждой строки из левой таблице есть две строки из правой таблицы с таким же ключом.

In [87]:
# В таблицах ключи не повторяются
left = pd.DataFrame({'key': ['A', 'B'],
                     'lval': [1, 2]})
right = pd.DataFrame({'key': ['A', 'B'],
                      'rval': [4, 5]})

In [88]:
left

  key  lval
0   A     1
1   B     2

In [89]:
right

  key  rval
0   A     4
1   B     5

In [90]:
pd.merge(left, right, on='key')

  key  lval  rval
0   A     1     4
1   B     2     5

В результате объединения получаем 2 строки &mdash; для каждой строки из левой таблице есть только одна строка из правой таблицы с таким же ключом.

Рассмотрим различные типы объединения. Сооздадим и напечатаем две таблицы.

In [91]:
left = pd.DataFrame({'lkey': ['A', 'B', 'C', 'A'],
                     'value': range(4)})
right = pd.DataFrame({'rkey': ['A', 'B', 'D', 'B'],
                      'value': range(4, 8)})

In [92]:
left

  lkey  value
0    A      0
1    B      1
2    C      2
3    A      3

In [93]:
right

  rkey  value
0    A      4
1    B      5
2    D      6
3    B      7

**Внешнее слияние** &mdash; используются ключи из объединения списков ключей. Иначе говоря, используются ключи, которые есть хотя бы в одной из таблиц. Если в другой таблице таких ключей нет, то ставятся пропуски.

In [94]:
pd.merge(left, right,
         left_on='lkey', right_on='rkey', how='outer')

  lkey  value_x rkey  value_y
0    A      0.0    A      4.0
1    A      3.0    A      4.0
2    B      1.0    B      5.0
3    B      1.0    B      7.0
4    C      2.0  NaN      NaN
5  NaN      NaN    D      6.0

**Внутреннее слияние** &mdash; используются ключи из пересечения списков ключей. Иначе говоря, используются ключи, которые присутствуют в обеих таблицах.

In [95]:
pd.merge(left, right,
         left_on='lkey', right_on='rkey', how='inner')

  lkey  value_x rkey  value_y
0    A        0    A        4
1    B        1    B        5
2    B        1    B        7
3    A        3    A        4

**Объединение по ключам левой таблицы.** Не используются ключи, которые есть в правой таблицы, но которых нет в левой. Если в правой таблице каких-то ключей нет, то ставятся пропуски.

In [96]:
pd.merge(left, right,
         left_on='lkey', right_on='rkey', how='left')

  lkey  value_x rkey  value_y
0    A        0    A      4.0
1    B        1    B      5.0
2    B        1    B      7.0
3    C        2  NaN      NaN
4    A        3    A      4.0

**Объединение по ключам правой таблицы.** Не используются ключи, которые есть в левой таблицы, но которых нет в правой. Если в левой таблице каких-то ключей нет, то ставятся пропуски.

In [97]:
pd.merge(left, right,
         left_on='lkey', right_on='rkey', how='right')

  lkey  value_x rkey  value_y
0    A      0.0    A        4
1    A      3.0    A        4
2    B      1.0    B        5
3  NaN      NaN    D        6
4    B      1.0    B        7

Выполним внутреннее объединение и установим ключ качестве индекса

In [98]:
pd.merge(left, right,
         left_on='lkey', right_on='rkey', how='inner') \
        .set_index('lkey')[['value_x', 'value_y']]

      value_x  value_y
lkey
A           0        4
B           1        5
B           1        7
A           3        4

## Группировка и сводные таблицы

Под группировкой (`"group by"`) понимаем процесс, включающий один или несколько следующих шагов:

- Разделение (`Splitting`) данных на группы по некоторым критериям.
- Независимое применение (`Applying`) функции к каждой группе.
- Объединение (`Combining`) результатов в структуру данных.

Подробнее см. в [Документации](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#groupby)

Группировка выполняется функцией

`df.groupby(by=None, axis=0, level=None, sort=True, ...)`

Результатом группировки является объект, состоящий из пар (имя группы, подтаблица). Имя группы соответствует значению, по которому произведена группировка. К объекту-результату группировки применимы, например, следующие операции:

* `for name, group in groupped: ... ` &mdash; цикл по группам;
* `get_group(name)` &mdash; получить таблицу, соответствующую группе с именем `name`;
* `groups` &mdash; получить все группы в виде словаря имя-подтаблица;
* `count()` &mdash; количество значений в группах, исключая пропуски;
* `size()` &mdash; размер групп;
* `sum()`, `max()`, `min()`;
* `mean()`, `median()`, `var()`, `std()`, `corr()`, `quantile(q)`;
* `describe()` &mdash; вывод описательных статистик;
* `aggregate(func)` &mdash; применение функции (или списка функций) `func` к группам.

In [ ]:
df = pd.DataFrame({
    'Животное' : ['Котик', 'Песик', 'Котик', 'Песик',
                  'Котик', 'Песик', 'Котик', 'Песик'],
    'Цвет шерсти' : ['белый', 'белый', 'коричневый', 'черный',
                     'коричневый', 'коричневый', 'белый', 'черный'],
    'Рост' : np.random.normal(5, 3, size=8),
    'Длина хвостика' : np.random.normal(10, 5, size=8)
})

df

  Животное Цвет шерсти       Рост  Длина хвостика
0    Котик       белый   4.964573        9.798898
1    Песик       белый   5.755154       20.015283
2    Котик  коричневый  -0.399278        8.070953
3    Песик      черный   8.007278       10.494533
4    Котик  коричневый   1.823567        3.331647
5    Песик  коричневый   0.152815        7.909495
6    Котик       белый   1.155659       10.522670
7    Песик      черный  10.696467       14.815434

In [ ]:
# Группировка, а затем применение функции mean() к полученным группам
# df.groupby('Животное').mean()

In [ ]:
df.groupby('Животное').describe()

          Рост                                                              \
         count      mean       std       min       25%       50%       75%
Животное
Котик      4.0  1.886130  2.253694 -0.399278  0.766925  1.489613  2.608819
Песик      4.0  6.152928  4.481143  0.152815  4.354569  6.881216  8.679575

                    Длина хвостика                                           \
                max          count       mean       std       min       25%
Животное
Котик      4.964573            4.0   7.931042  3.234163  3.331647  6.886126
Песик     10.696467            4.0  13.308686  5.301555  7.909495  9.848273


                50%        75%        max
Животное
Котик      8.934925   9.979841  10.522670
Песик     12.654983  16.115396  20.015283

In [ ]:
# Группировка по двум колонкам и последующее применение операции суммирования
df.groupby(['Животное', 'Цвет шерсти']).sum()

                           Рост  Длина хвостика
Животное Цвет шерсти
Котик    белый         6.120232       20.321568
         коричневый    1.424289       11.402600
Песик    белый         5.755154       20.015283
         коричневый    0.152815        7.909495
         черный       18.703745       25.309966

Полученная таблица имеет мультииндекс

In [ ]:
df.groupby(['Животное', 'Цвет шерсти']).sum().index

MultiIndex([('Котик',      'белый'),
            ('Котик', 'коричневый'),
            ('Песик',      'белый'),
            ('Песик', 'коричневый'),
            ('Песик',     'черный')],
           names=['Животное', 'Цвет шерсти'])

Метод [`stack()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html#pandas.DataFrame.stack) "сжимает" уровень в столбцах DataFrame.

In [ ]:
stacked = df.stack()
stacked

0  Животное               Котик
   Цвет шерсти            белый
   Рост                4.964573
   Длина хвостика      9.798898
1  Животное               Песик
   Цвет шерсти            белый
   Рост                5.755154
   Длина хвостика     20.015283
2  Животное               Котик
   Цвет шерсти       коричневый
   Рост               -0.399278
   Длина хвостика      8.070953
3  Животное               Песик
   Цвет шерсти           черный
   Рост                8.007278
   Длина хвостика     10.494533
4  Животное               Котик
   Цвет шерсти       коричневый
   Рост                1.823567
   Длина хвостика      3.331647
5  Животное               Песик
   Цвет шерсти       коричневый
   Рост                0.152815
   Длина хвостика      7.909495
6  Животное               Котик
   Цвет шерсти            белый
   Рост                1.155659
   Длина хвостика      10.52267
7  Животное               Песик
   Цвет шерсти           черный
   Рост               10.696467
   Длина хвостика     14.815434
dtype: object

С "уложенными" (`"stacked"`) DataFrame или Series (имеющими MultiIndex в качестве индекса) обратная операция - [`unstack()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.unstack.html#pandas.DataFrame.unstack), которая по умолчанию распаковывает последний уровень:

In [ ]:
stacked.unstack()

  Животное Цвет шерсти       Рост Длина хвостика
0    Котик       белый   4.964573       9.798898
1    Песик       белый   5.755154      20.015283
2    Котик  коричневый  -0.399278       8.070953
3    Песик      черный   8.007278      10.494533
4    Котик  коричневый   1.823567       3.331647
5    Песик  коричневый   0.152815       7.909495
6    Котик       белый   1.155659       10.52267
7    Песик      черный  10.696467      14.815434

### Сводные таблицы (Pivot tables)

См. секцию [Документации](https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html#reshaping-pivot)

In [ ]:
df = pd.DataFrame({'A': ['one', 'one', 'two', 'three'] * 3,
                   'B': ['A', 'B', 'C'] * 4,
                   'C': ['red', 'red', 'red', 'blue', 'blue', 'blue'] * 2,
                   'D': np.random.randn(12),
                   'E': np.random.randn(12)})
df

        A  B     C         D         E
0     one  A   red -0.589847  0.605587
1     one  B   red -0.169090  0.293492
2     two  C   red -0.860891  0.223029
3   three  A  blue  1.583754 -1.831923
4     one  B  blue -0.528759  0.157143
5     one  C  blue -1.251660  1.206033
6     two  A   red -1.549921 -0.381358
7   three  B   red -0.512406  0.048252
8     one  C   red  0.066463 -0.781041
9     one  A  blue -1.433407 -0.598688
10    two  B  blue -0.370832 -1.312417
11  three  C  blue -1.606957 -0.873750

Мы можем очень легко создать сводные таблицы из этих данных:

In [ ]:
pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C'])

C            blue       red
A     B
one   A -1.433407 -0.589847
      B -0.528759 -0.169090
      C -1.251660  0.066463
three A  1.583754       NaN
      B       NaN -0.512406
      C -1.606957       NaN
two   A       NaN -1.549921
      B -0.370832       NaN
      C       NaN -0.860891

## Временные ряды

pandas имеет простые, мощные и эффективные функции для выполнения операций передискретизации во время преобразования частоты (например, преобразование секундных данных в 5-минутные данные). См. [документацию по временным рядам](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries).

In [ ]:
rng = pd.date_range('1/1/2012', periods=100, freq='S')
rng[:10]

DatetimeIndex(['2012-01-01 00:00:00', '2012-01-01 00:00:01',
               '2012-01-01 00:00:02', '2012-01-01 00:00:03',
               '2012-01-01 00:00:04', '2012-01-01 00:00:05',
               '2012-01-01 00:00:06', '2012-01-01 00:00:07',
               '2012-01-01 00:00:08', '2012-01-01 00:00:09'],
              dtype='datetime64[ns]', freq='S')

In [ ]:
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)
ts[:10]

2012-01-01 00:00:00    244
2012-01-01 00:00:01    344
2012-01-01 00:00:02    429
2012-01-01 00:00:03    450
2012-01-01 00:00:04    242
2012-01-01 00:00:05    393
2012-01-01 00:00:06    253
2012-01-01 00:00:07    228
2012-01-01 00:00:08    319
2012-01-01 00:00:09     95
Freq: S, dtype: int64

In [ ]:
ts.resample('5Min').sum()

2012-01-01    25068
Freq: 5T, dtype: int64

Представление часового пояса:

In [ ]:
rng = pd.date_range('3/6/2012 00:00', periods=5, freq='D')
rng

DatetimeIndex(['2012-03-06', '2012-03-07', '2012-03-08', '2012-03-09',
               '2012-03-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
ts = pd.Series(np.random.randn(len(rng)), rng)
ts

2012-03-06    1.749809
2012-03-07   -0.221322
2012-03-08   -0.446608
2012-03-09   -1.309222
2012-03-10    1.074737
Freq: D, dtype: float64

In [ ]:
ts

2012-03-06    1.749809
2012-03-07   -0.221322
2012-03-08   -0.446608
2012-03-09   -1.309222
2012-03-10    1.074737
Freq: D, dtype: float64

In [ ]:
ts_utc = ts.tz_localize('UTC')
ts_utc

2012-03-06 00:00:00+00:00    1.749809
2012-03-07 00:00:00+00:00   -0.221322
2012-03-08 00:00:00+00:00   -0.446608
2012-03-09 00:00:00+00:00   -1.309222
2012-03-10 00:00:00+00:00    1.074737
Freq: D, dtype: float64

Преобразование в другой часовой пояс:

In [ ]:
ts_utc.tz_convert('US/Eastern')

2012-03-05 19:00:00-05:00    1.749809
2012-03-06 19:00:00-05:00   -0.221322
2012-03-07 19:00:00-05:00   -0.446608
2012-03-08 19:00:00-05:00   -1.309222
2012-03-09 19:00:00-05:00    1.074737
Freq: D, dtype: float64

Преобразование между представлениями промежутка времени:

In [ ]:
rng = pd.date_range('1/1/2012', periods=5, freq='M')
rng

DatetimeIndex(['2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30',
               '2012-05-31'],
              dtype='datetime64[ns]', freq='M')

In [ ]:
ts = pd.Series(np.random.randn(len(rng)), index=rng)
ts

2012-01-31    0.423445
2012-02-29    0.579950
2012-03-31    0.055710
2012-04-30   -1.367287
2012-05-31   -0.634377
Freq: M, dtype: float64

In [ ]:
ps = ts.to_period()
ps

2012-01    0.423445
2012-02    0.579950
2012-03    0.055710
2012-04   -1.367287
2012-05   -0.634377
Freq: M, dtype: float64

In [ ]:
ps.to_timestamp()

2012-01-01    0.423445
2012-02-01    0.579950
2012-03-01    0.055710
2012-04-01   -1.367287
2012-05-01   -0.634377
Freq: MS, dtype: float64

Преобразование между периодом и меткой времени позволяет использовать некоторые удобные арифметические функции. В следующем примере мы преобразуем ежеквартальную частоту с годом, заканчивающимся в ноябре, в 9 утра конца месяца, следующего за концом квартала:

In [ ]:
prng = pd.period_range('2022Q1', '2023Q4', freq='Q-NOV')
prng

PeriodIndex(['2022Q1', '2022Q2', '2022Q3', '2022Q4', '2023Q1', '2023Q2',
             '2023Q3', '2023Q4'],
            dtype='period[Q-NOV]')

In [ ]:
ts = pd.Series(np.random.randn(len(prng)), prng)
ts[:10]

2022Q1    0.202924
2022Q2    0.932022
2022Q3    0.147423
2022Q4    1.064807
2023Q1   -1.028559
2023Q2    0.038347
2023Q3   -0.765529
2023Q4    0.138185
Freq: Q-NOV, dtype: float64

In [ ]:
ts.index = (prng.asfreq('M', 'e') + 1).asfreq('H', 's') + 9
ts[:10]

2022-03-01 09:00    0.202924
2022-06-01 09:00    0.932022
2022-09-01 09:00    0.147423
2022-12-01 09:00    1.064807
2023-03-01 09:00   -1.028559
2023-06-01 09:00    0.038347
2023-09-01 09:00   -0.765529
2023-12-01 09:00    0.138185
Freq: H, dtype: float64

In [ ]:
ts.head()

2022-03-01 09:00    0.202924
2022-06-01 09:00    0.932022
2022-09-01 09:00    0.147423
2022-12-01 09:00    1.064807
2023-03-01 09:00   -1.028559
Freq: H, dtype: float64

## Новая и улучшенная агрегатная функция

## Новая и улучшенная агрегатная функция

В pandas 0.20.0 была добавлена функция [`agg`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.agg.html), которая значительно упрощает суммирование данных аналогично groupby.

Чтобы проиллюстрировать ее функциональность, предположим, что нам нужно получить сумму в столбцах `D` и `E`, а также среднее значение столбца `E`.

Процесс не очень удобный:

In [ ]:
df

        A  B     C         D         E
0     one  A   red -0.589847  0.605587
1     one  B   red -0.169090  0.293492
2     two  C   red -0.860891  0.223029
3   three  A  blue  1.583754 -1.831923
4     one  B  blue -0.528759  0.157143
5     one  C  blue -1.251660  1.206033
6     two  A   red -1.549921 -0.381358
7   three  B   red -0.512406  0.048252
8     one  C   red  0.066463 -0.781041
9     one  A  blue -1.433407 -0.598688
10    two  B  blue -0.370832 -1.312417
11  three  C  blue -1.606957 -0.873750

In [ ]:
df[["D", "E"]].sum()

D   -7.223554
E   -3.245641
dtype: float64

In [ ]:
df["E"].mean()

-0.27047010427720863

Это работает, но нужно дополнительно пояснять что было сделано.

Новый `agg` упрощает процесс и на выходе таблица со значениями.

In [ ]:
df[["D", "E"]].agg(['sum', 'mean'])

             D         E
sum  -7.223554 -3.245641
mean -0.601963 -0.270470

Другая запись будет выглядеть следующим образом. Укажем для столбцов явно какие столбцы в `agg` и укажем, какие операции применять к каждому столбцу.

In [ ]:
df.agg({'E': ['sum', 'mean'], 'D': ['sum']})

             E         D
sum  -3.245641 -7.223554
mean -0.270470       NaN

Чтобы агрегировать данные и использовать функцию `mode` по работе с текстом, применим лямбда-функцию, которая использует `value_counts`:

In [ ]:
get_max = lambda x: x.value_counts(dropna=False)

Затем, включить наиболее часто используемые  значения в сводную таблицу:

In [ ]:
df

        A  B     C         D         E
0     one  A   red -0.589847  0.605587
1     one  B   red -0.169090  0.293492
2     two  C   red -0.860891  0.223029
3   three  A  blue  1.583754 -1.831923
4     one  B  blue -0.528759  0.157143
5     one  C  blue -1.251660  1.206033
6     two  A   red -1.549921 -0.381358
7   three  B   red -0.512406  0.048252
8     one  C   red  0.066463 -0.781041
9     one  A  blue -1.433407 -0.598688
10    two  B  blue -0.370832 -1.312417
11  three  C  blue -1.606957 -0.873750

In [ ]:
df.agg({'D': ['sum', 'mean'], 'E': ['sum', 'mean'], 'A': [get_max]})

              D         E        A
              D         E <lambda>
sum   -7.223554 -3.245641      NaN
mean  -0.601963 -0.270470      NaN
one         NaN       NaN      6.0
two         NaN       NaN      3.0
three       NaN       NaN      3.0

In [ ]:
get_max.__name__ = "most frequent"

Но в этом подходе: в столбце написано `<lambda>`.

В идеале указать `most frequent` (*наиболее часто*). Можно явно поменять название функции:

In [ ]:
get_max.__name__ = "most frequent"

Теперь, агрегирование:

In [ ]:
df.agg({'D': ['sum', 'mean'], 'E': ['sum', 'mean'], 'A': [get_max]})

              D         E             A
              D         E most frequent
sum   -7.223554 -3.245641           NaN
mean  -0.601963 -0.270470           NaN
one         NaN       NaN           6.0
two         NaN       NaN           3.0
three       NaN       NaN           3.0

В качестве завершения финальный бонус.

Агрегатная (aggregate) функция, использующая словарь, полезна, но проблема заключается в том, что она не сохраняет порядок.

Если необходимо убедиться, что столбцы расположены в определенном порядке, можно использовать [`OrderedDict`](https://docs.python.org/3/library/collections.html#collections.OrderedDict):

In [ ]:
import collections
f = collections.OrderedDict([('A', [get_max]), ('D', ['sum', 'mean']), ('E', ['sum', 'mean'])])
df.agg(f)

                  A         D         E
      most frequent         D         E
one             6.0       NaN       NaN
two             3.0       NaN       NaN
three           3.0       NaN       NaN
sum             NaN -7.223554 -3.245641
mean            NaN -0.601963 -0.270470

## Получение и запись данных

### CSV

см. [про запись в csv файлы](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-store-in-csv)

In [ ]:
df.to_csv('foo.csv')

см. [про чтенеи csv файлов](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-read-csv-table)

In [ ]:
pd.read_csv('foo.csv')

    Unnamed: 0      A  B     C         D         E
0            0    one  A   red -1.858931 -0.573762
1            1    one  B   red -2.479307  1.908843
2            2    two  C   red -0.337012 -0.075287
3            3  three  A  blue  1.969856 -0.597402
4            4    one  B  blue  0.245826 -0.264284
5            5    one  C  blue  0.725448  0.417956
6            6    two  A   red -0.265341 -1.036288
7            7  three  B   red -0.441735 -1.119077
8            8    one  C   red -0.471247  0.846928
9            9    one  A  blue  0.384062  0.242129
10          10    two  B  blue  1.303241 -0.530112
11          11  three  C  blue -0.085511  0.087011

### HDF5

см. про чтение и запись в [`HDFStores`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-hdf5)

Запись в `HDF5` хранилище:

In [ ]:
df.to_hdf('foo.h5', 'df')

Чтение из `HDF5` хранилища:

In [ ]:
pd.read_hdf('foo.h5', 'df')

        A  B     C         D         E
0     one  A   red -1.858931 -0.573762
1     one  B   red -2.479307  1.908843
2     two  C   red -0.337012 -0.075287
3   three  A  blue  1.969856 -0.597402
4     one  B  blue  0.245826 -0.264284
5     one  C  blue  0.725448  0.417956
6     two  A   red -0.265341 -1.036288
7   three  B   red -0.441735 -1.119077
8     one  C   red -0.471247  0.846928
9     one  A  blue  0.384062  0.242129
10    two  B  blue  1.303241 -0.530112
11  three  C  blue -0.085511  0.087011

### Excel

см. [про чтение и запись в MS Excel](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-excel)

Запись в excel файл:

In [ ]:
df.to_excel('foo.xlsx', sheet_name='Sheet1')

Чтение из excel файла:

In [ ]:
pd.read_excel('foo.xlsx', 'Sheet1', index_col=None, na_values=['NA'])

    Unnamed: 0      A  B     C         D         E
0            0    one  A   red -1.858931 -0.573762
1            1    one  B   red -2.479307  1.908843
2            2    two  C   red -0.337012 -0.075287
3            3  three  A  blue  1.969856 -0.597402
4            4    one  B  blue  0.245826 -0.264284
5            5    one  C  blue  0.725448  0.417956
6            6    two  A   red -0.265341 -1.036288
7            7  three  B   red -0.441735 -1.119077
8            8    one  C   red -0.471247  0.846928
9            9    one  A  blue  0.384062  0.242129
10          10    two  B  blue  1.303241 -0.530112
11          11  three  C  blue -0.085511  0.087011